#!/bin/sh
#
# COPYRIGHT (c) 2012 The Fellowship of SML/NJ (http://www.smlnj.org)
# All rights reserved.
#
# script to compile using the batch compiler
# usage:
#	cmb-make [ <sml-cmd> ] <flags> ...
#
# Do a batch compiler of the compiler; the optional <sml-cmd> argument specifes
# the path to the SML compiler to use for the build.
#

set -x

SML=sml

if test $# -ge 1 ; then
  case $1 in
    -C*) ;; # ignore compiler flags
    *) SML=$1
       shift
    ;;
  esac
fi

exec $SML $@ -DNO_PLUGINS '$smlnj/cmb.cm' <<XXXX
CMB.make();
XXXX
