/* ml_pathconf.h
 *
 * This file is generated by gen-posix-names.sh
 */
#ifdef _PC_ABI_AIO_XFER_MAX
  {"ABI_AIO_XFER_MAX",  _PC_ABI_AIO_XFER_MAX},
#endif
#ifdef _PC_ABI_ASYNC_IO
  {"ABI_ASYNC_IO",  _PC_ABI_ASYNC_IO},
#endif
#ifdef _PC_ASYNC_IO
  {"ASYNC_IO",  _PC_ASYNC_IO},
#endif
#ifdef _PC_CHOWN_RESTRICTED
  {"CHOWN_RESTRICTED",  _PC_CHOWN_RESTRICTED},
#endif
#ifdef _PC_FILESIZEBITS
  {"FILESIZEBITS",  _PC_FILESIZEBITS},
#endif
#ifdef _PC_LINK_MAX
  {"LINK_MAX",  _PC_LINK_MAX},
#endif
#ifdef _PC_MAX_CANON
  {"MAX_CANON",  _PC_MAX_CANON},
#endif
#ifdef _PC_MAX_INPUT
  {"MAX_INPUT",  _PC_MAX_INPUT},
#endif
#ifdef _PC_NAME_MAX
  {"NAME_MAX",  _PC_NAME_MAX},
#endif
#ifdef _PC_NO_TRUNC
  {"NO_TRUNC",  _PC_NO_TRUNC},
#endif
#ifdef _PC_PATH_MAX
  {"PATH_MAX",  _PC_PATH_MAX},
#endif
#ifdef _PC_PIPE_BUF
  {"PIPE_BUF",  _PC_PIPE_BUF},
#endif
#ifdef _PC_PRIO_IO
  {"PRIO_IO",  _PC_PRIO_IO},
#endif
#ifdef _PC_SYNC_IO
  {"SYNC_IO",  _PC_SYNC_IO},
#endif
#ifdef _PC_VDISABLE
  {"VDISABLE",  _PC_VDISABLE},
#endif
