= The `Random` structure
:Author: John Reppy
:Date: {release-date}
:stem: latexmath
:source-highlighter: pygments
:VERSION: {smlnj-version}

The `Random` structure implements a random number generator using a
__subtract-with-borrow__ (SWB) generator as described in Marsaglia
and Zaman, "https://doi.org/10.1214/aoap/1177005878[__A New Class of
Random Number Generators__]," Annuals of Applied Probability 1(3), 1991,
pp. 462-480.

The SWB generator is a 31-bit generator with lags 48 and 8. It has period
(2^1487^ - 2^247^) / 105 or about 10^445^. In general, these generators are
excellent. They act locally like a lagged Fibonacci generator. however,
and thus have troubles with the birthday test. Thus, we combine this SWB
generator with the linear congruential generator (48271 \* a) mod (2^31^ - 1).

Although the interface is fairly abstract, the implementation uses
31-bit ML words. At some point, it might be good to use 32-bit words.

== Synopsis

[source,sml]
------------
structure Random
------------

== Interface

[source,sml]
------------
type rand

val rand : (int * int) -> rand

val toString : rand -> string
val fromString : string -> rand

val randInt : rand -> int

val randNat : rand -> int

val randReal : rand -> real

val randRange : (int * int) -> rand -> int
------------

== Description

`[.kw]#type# rand`::
  Represents the internal state of a random number generator.

`[.kw]#val# rand : (int * int) \-> rand`::
  `rand (n1, n2)` creates a random number generator from the
  initial seed specified by the pair `(n1, n2)`.

`[.kw]#val# toString : rand \-> string`::
  something
`[.kw]#val# fromString : string \-> rand`::
  something
        (* convert state to and from string
         * fromString raises Fail if its argument
         * does not have the proper form.
         *)

`[.kw]#val# randInt : rand \-> int`::
  something
	(* generate ints uniformly in [minInt,maxInt] *)

`[.kw]#val# randNat : rand \-> int`::
  something
	(* generate ints uniformly in [0,maxInt] *)

`[.kw]#val# randReal : rand \-> real`::
  something
	(* generate reals uniformly in [0.0,1.0) *)

`[.kw]#val# randRange : (int * int) \-> rand \-> int`::
  something
	(* randRange (lo,hi) generates integers uniformly [lo,hi].
	 * Raises Fail if hi < lo.
	 *)

== See Also

xref:str-Rand.adoc[`Rand`],
xref:smlnj-lib.adoc[__The Util Library__]
