= The `JSONUtil` structure
:Author: John Reppy
:Date: {release-date}
:stem: latexmath
:source-highlighter: pygments
:VERSION: {smlnj-version}

some overview

== Synopsis

[source,sml]
------------
structure JSONUtil
------------

== Interface

[source,sml]
------------
exception NotBool of JSON.value
exception NotInt of JSON.value
exception NotNumber of JSON.value
exception NotString of JSON.value

exception NotObject of JSON.value

exception FieldNotFound of JSON.value * string

exception NotArray of JSON.value

exception ArrayBounds of JSON.value * int

val exnMessage : exn -> string

val asBool : JSON.value -> bool
val asInt : JSON.value -> Int.int
val asIntInf : JSON.value -> IntInf.int
val asNumber : JSON.value -> Real.real
val asString : JSON.value -> string

val findField : JSON.value -> string -> JSON.value option

val lookupField : JSON.value -> string -> JSON.value

val asArray : JSON.value -> JSON.value vector

val arrayMap : (JSON.value -> 'a) -> JSON.value -> 'a list

datatype edge = SUB of int | SEL of string

type path = edge list

val get : JSON.value * path -> JSON.value

val replace : JSON.value * path * JSON.value -> JSON.value

val insert : JSON.value * path * string * JSON.value -> JSON.value

val append : JSON.value * path * JSON.value list -> JSON.value
------------

== Description

`[.kw]#exception# NotBool [.kw]#of# JSON.value`::
  [[exn:NotBool]]
  raised by the

`[.kw]#exception# NotInt [.kw]#of# JSON.value`::
  [[exn:NotInt]]
  raised if ...

`[.kw]#exception# NotNumber [.kw]#of# JSON.value`::
  [[exn:NotNumber]]
  raised if ...

`[.kw]#exception# NotString [.kw]#of# JSON.value`::
  [[exn:NotString]]
  raised if ...

`[.kw]#exception# NotObject [.kw]#of# JSON.value`::
  [[exn:NotObject]]
  raised if ...

`[.kw]#exception# FieldNotFound [.kw]#of# JSON.value * string`::
  [[exn:FieldNotFound]]
  This exception is raised when the given field is not found in an object.

`[.kw]#exception# NotArray [.kw]#of# JSON.value`::
  [[exn:NotArray]]
  This exception is raised when trying to process a non-array value as an array.

`[.kw]#exception# ArrayBounds [.kw]#of# JSON.value * int`::
  [[exn:ArrayBounds]]
  This exception is raised when access to an array value is out of bounds.

  (* map the above exceptions to a message string; we use General.exnMessage for other
   * exceptions.
   *)
`[.kw]#val# exnMessage : exn -> string`::
  `exnMessage exn` returns an error-message string for the exception value
  `exn`.  This function produces specialized messages for the exceptions defined
  in the `JSONUtil` structure and falls back to the
  {sml-basis-url}/general.html#SIG:GENERAL.exnMessage:VAL[General.exnMessage]
  function for other exceptions.

`[.kw]#val# asBool : JSON.value -> bool`::
  `asBool (JSON.BOOL b)` returns the value `b`.  This function raises
  the xref:exn:NotBool[`NotBool`] exception if the value is not a
  *JSON* boolean value.

`[.kw]#val# asInt : JSON.value -> int`::
  `asInt (JSON.INT n)` returns the value `n` converted to `int`.
  This function raises the xref:exn:NotInt[`NotInt`] exception if the
  value is not a *JSON* integer value.  It may also raise the
  {sml-basis-url}/general.html#SIG:GENERAL.Overflow:EXN[`Overflow`]
  exception if `n` is too large for the default `int` type.

`[.kw]#val# asIntInf : JSON.value -> IntInf.int`::
  `asIntInf (JSON.INT n)` returns the value `n`.
  This function raises the xref:exn:NotInt[`NotInt`] exception if the
  value is not a *JSON* integer value.

`[.kw]#val# asNumber : JSON.value -> Real.real`::
  `asNumber jv` converts the *JSON* number `jv` to an SML `real` value.
  The `jv` argument can either have the form `JSON.INT n`, in which case
  `n` is converted to the `real` type and returned, or `JSON.FLOAT f`,
  in which case `f` is returned; otherwise, the
  xref:exn:NotNumber[`NotNumber`] exception is raised.

`[.kw]#val# asString : JSON.value -> string`::
  `asBool (JSON.STRING s)` returns the value `s`.  This function raises
  the xref:exn:NotString[`NotString`] exception if the value is not a
  *JSON* string value.

  (* find a field in an object; this function raises the NotObject exception when
   * the supplied value is not an object.
   *)
`[.kw]#val# findField : JSON.value -> string -> JSON.value option`::
  `findField (JSON.OBJECT flds) key` returns `SOME jv` when the
  list of fields `flds` contains `(key, jv)` and `NONE` otherwise.
  If `findField` is called on a value that is not a *JSON* object,
  then it raises the xref:exn:NotObject[`NotObject`] exception.

  (* lookup a field in an object; this function raises the NotObject exception when
   * the supplied value is not an object and raises FieldNotFound if the value is
   * an object, but does not have the specified field.
   *)
`[.kw]#val# lookupField : JSON.value -> string -> JSON.value`::
  something

  (* convert a JSON array to an SML vector *)
`[.kw]#val# asArray : JSON.value -> JSON.value vector`::
  something

`[.kw]#val# arrayMap : (JSON.value -> 'a) -> JSON.value -> 'a list`::
  map a conversion function over a JSON array to produce a list; this function
  raises the xref:exn:NotArray[`NotArray`] exception if the second argument
  is not an array.

`[.kw]#datatype# edge = ...`::
  path specification for indexing into JSON values
+
--
    `SUB [.kw]#of# int`::
	index into array component
    `SEL [.kw]#of# string`::
	select field of object
--

`[.kw]#type# path = edge list`::
  something


`[.kw]#val# get : JSON.value * path \-> JSON.value`::
  `get (jv, path)` returns the component of `jv` named by `path`.  It raises
  one of the xref:exn:NotObject[`NotObject`], xref:exn:NotArray[`NotArray`],
  or xref:exn:FieldNotFound[`FieldNotFound`] exceptions if there is an
  inconsistency between the path and the structure of `jv`.

== See Also

link:json.html[`JSON`]
link:json-lib.html[`json-lib`]
