hello there
[Loading CompVax]
[Loading VaxGlue]
[Loading VaxCodes]
[Loading VaxMCode]
[Loading BasicVax]
[Loading Backpatch]
[Loading Dynamic]
[Loading ErrorMsg]
[Executing ErrorMsg]
[Executing Dynamic]
[Executing Backpatch]
[Executing BasicVax]
[Loading BitOps]
[Executing BitOps]
[Loading RealConst]
[Loading Bigint]
[Executing Bigint]
[Executing RealConst]
[Executing VaxMCode]
[Loading VaxAsCode]
[Loading VaxAssem]
[Executing VaxAssem]
[Executing VaxAsCode]
[Loading VaxPeephole]
[Executing VaxPeephole]
[Loading VaxGen]
[Loading VaxPrim]
[Loading Symbols]
[Loading Symbol]
[Executing Symbol]
[Loading Token]
[Executing Token]
[Executing Symbols]
[Loading Prim]
[Loading Access]
[Executing Access]
[Loading Basics]
[Loading Table]
[Executing Table]
[Loading PrintUtil]
[Executing PrintUtil]
[Executing Basics]
[Loading Sort]
[Executing Sort]
[Loading BasicTypes]
[Loading Tuples]
[Executing Tuples]
[Executing BasicTypes]
[Executing Prim]
[Loading EnvAccess]
[Loading Env]
[Loading EnvBind]
[Executing EnvBind]
[Loading EnvFunc]
[Executing EnvFunc]
[Executing Env]
[Loading PrintType]
[Loading List2]
[Executing List2]
[Executing PrintType]
[Loading Ascii]
[Executing Ascii]
[Loading Intmap]
[Executing Intmap]
[Loading BinSort]
[Executing BinSort]
[Loading TypesUtil]
[Executing TypesUtil]
[Loading Absyn]
[Loading BareAbsyn]
[Executing BareAbsyn]
[Executing Absyn]
[Executing EnvAccess]
[Loading CGoptions]
[Executing CGoptions]
[Executing VaxPrim]
[Executing VaxGen]
[Executing VaxCodes]
[Loading Invoke]
[Loading Lambda]
[Loading PrintBasics]
[Executing PrintBasics]
[Executing Lambda]
[Loading Codegen]
[Loading Switcher]
[Executing Switcher]
[Loading Codenv]
[Loading Opt]
[Loading Intset]
[Executing Intset]
[Executing Opt]
[Executing Codenv]
[Executing Codegen]
[Loading MCprint]
[Loading PrintAbsyn]
[Executing PrintAbsyn]
[Executing MCprint]
[Loading Typecheck]
[Loading Overload]
[Executing Overload]
[Executing Typecheck]
[Loading Translate]
[Loading Unboxed]
[Executing Unboxed]
[Loading Equal]
[Executing Equal]
[Loading Nonrec]
[Executing Nonrec]
[Loading MC]
[Loading MCopt]
[Executing MCopt]
[Executing MC]
[Executing Translate]
[Loading PrintDec]
[Loading PrintVal]
[Executing PrintVal]
[Executing PrintDec]
[Loading Parse]
[Loading Topsort]
[Executing Topsort]
[Loading ConRep]
[Executing ConRep]
[Loading Sharing]
[Loading Siblings]
[Loading Unionfind]
[Executing Unionfind]
[Executing Siblings]
[Executing Sharing]
[Loading SigMatch]
[Executing SigMatch]
[Loading FirstSets]
[Loading Lex]
[Loading CharBuffer]
[Executing CharBuffer]
[Executing Lex]
[Executing FirstSets]
[Executing Parse]
[Executing Invoke]
[Executing VaxGlue]
[Loading Compile]
[Loading M68options]
[Executing M68options]
[Executing Compile]
[Executing CompVax]
[Loading boot/perv.sig]
signature REF
signature LIST
signature ARRAY
signature BYTEARRAY
signature BASICIO
signature IO
signature BOOL
signature STRING
signature INTEGER
signature REAL
signature GENERAL
signature PERVASIVES
[closing boot/perv.sig]
[Loading boot/assembly.sig]
signature ASSEMBLY
[closing boot/assembly.sig]
[Loading boot/system.sig]
signature RUNTIMECONTROL
signature MCCONTROL
signature CGCONTROL
signature PRINTCONTROL
signature CONTROL
signature TIMER
signature TAGS
signature STATS
signature SYSTEM
[closing boot/system.sig]
[Compiling boot/math.sml]
signature MATH
functor Math

Closure: v842

Closure: v227
BOGUS : Path [0,0]

Closure: v794 v811 v817 v821 v264
v227 : Path [~1,0]
v834 : Known
v835 : Known
v836 : Known
v838 : Path [~8,0]
v839 : Path [~7,0]
v840 : Path [~6,0]
link to BOGUS : Path [0,0]

Closure: v785
v788 : Known
v789 : Known
v790 : Known
v791 : Known
v792 : Known
v793 : Known
link to BOGUS : Path [0,0]

Closure: v776
v779 : Known
v780 : Known
v781 : Known
v782 : Known
v783 : Known
v784 : Known
link to BOGUS : Path [0,0]

Closure: v739 v752 v760 v767
v770 : Known
v771 : Known
v772 : Known
v773 : Known
v774 : Known
v775 : Known
v776 : Path [~11,0]
v785 : Path [~10,0]
v794 : Path [~9,0]
v817 : Path [~9,2]
v821 : Path [~9,3]
v833 : Known
v834 : Known
v835 : Known
link to BOGUS : Path [0,0]

Closure: v717
v735 : Known
v736 : Known
v737 : Known
v738 : Known
v817 : Path [~9,2]
v821 : Path [~9,3]
v834 : Known
v835 : Known
v836 : Known
link to BOGUS : Path [0,0]

Closure: v691
v227 : Path [~1,0]
v229 : Path [~4,0]
v264 : Path [~9,4]
v711 : Known
v712 : Known
v713 : Known
v715 : Known
v716 : Known
v717 : Path [~13,0]
v821 : Path [~9,3]
v834 : Known
v836 : Known
v838 : Path [~8,0]
v840 : Path [~6,0]
link to BOGUS : Path [0,0]

Closure: v650 v681
v227 : Path [~1,0]
v230 : Path [~5,0]
v264 : Path [~9,4]
v684 : Known
v685 : Known
v686 : Known
v687 : Known
v688 : Known
v689 : Known
v690 : Known
v714 : Known
v715 : Known
v716 : Known
v833 : Known
v835 : Known
v836 : Known
v837 : Known
v839 : Path [~7,0]
v840 : Path [~6,0]
link to BOGUS : Path [0,0]

Closure: v490 v567 v571
v227 : Path [~1,0]
v228 : Path [~3,0]
v633 : Known
v634 : Known
v635 : Known
v636 : Known
v637 : Known
v638 : Known
v639 : Known
v640 : Known
v641 : Known
v642 : Known
v643 : Known
v644 : Known
v645 : Known
v646 : Known
v647 : Known
v648 : Known
v649 : Known
v772 : Known
v774 : Known
v775 : Known
v821 : Path [~9,3]
v832 : Known
v833 : Known
v834 : Known
v836 : Known
v838 : Path [~8,0]
v839 : Path [~7,0]
v840 : Path [~6,0]
link to BOGUS : Path [0,0]

Closure: v595
v405 : Path [~7,0]
v625 : Path [~6,0]
v626 : Path [~5,0]
v633 : Path [0,~2]

Closure: v497
v438 : Path [~1,0]
v832 : Path [0,0]

Closure: v464
v832 : Path [0,0]

Closure: v656
v264 : Path [~1,0]
v366 : Path [0,0]

Closure: v698
v264 : Path [~1,0]
v344 : Path [0,0]

Closure: v317
link to closure of v739 : Path [0,0]

Closure: v848
link to closure of v739 : Path [0,0]
[closing boot/math.sml]
[Compiling boot/perv.sml]
functor PervFunc

Closure: v3188

Closure: v850
v489 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v3189
link to closure of v489 : Path [0,0]

Closure: v3190
link to closure of v489 : Path [0,0]

Closure: v3191
link to closure of v489 : Path [0,0]

Closure: v3192
link to closure of v489 : Path [0,0]

Closure: v3193
link to closure of v489 : Path [0,0]

Closure: v3194
link to closure of v489 : Path [0,0]

Closure: v3195
link to closure of v489 : Path [0,0]

Closure: v3196
link to closure of v489 : Path [0,0]

Closure: v3197
link to closure of v489 : Path [0,0]

Closure: v3198
link to closure of v489 : Path [0,0]

Closure: v3199
link to closure of v489 : Path [0,0]

Closure: v3200
link to closure of v489 : Path [0,0]

Closure: v3201
link to closure of v489 : Path [0,0]

Closure: v3202
link to closure of v489 : Path [0,0]

Closure: v3203
link to closure of v489 : Path [0,0]

Closure: v3204
link to closure of v489 : Path [0,0]

Closure: v3205
link to closure of v489 : Path [0,0]

Closure: v3206
link to closure of v489 : Path [0,0]

Closure: v3207
link to closure of v489 : Path [0,0]

Closure: v3208
link to closure of v489 : Path [0,0]

Closure: v3209
link to closure of v489 : Path [0,0]

Closure: v3210
link to closure of v489 : Path [0,0]

Closure: v3211
link to closure of v489 : Path [0,0]

Closure: v3212
link to closure of v489 : Path [0,0]

Closure: v3213
link to closure of v489 : Path [0,0]

Closure: v3214
link to closure of v489 : Path [0,0]

Closure: v3215
link to closure of v489 : Path [0,0]

Closure: v3216
link to closure of v489 : Path [0,0]

Closure: v3217
link to closure of v489 : Path [0,0]

Closure: v3218
link to closure of v489 : Path [0,0]

Closure: v3219
link to closure of v489 : Path [0,0]

Closure: v3220
link to closure of v489 : Path [0,0]

Closure: v3221
link to closure of v489 : Path [0,0]

Closure: v3222
link to closure of v489 : Path [0,0]

Closure: v3180 v3183
link to closure of v489 : Path [0,0]

Closure: v3223
link to closure of v489 : Path [0,0]

Closure: v3224
link to closure of v489 : Path [0,0]

Closure: v3060 v3084 v3095 v3105 v3116 v3127 v3136 v3163 v3166 v3173 v910 v916 v971
v895 : Path [~5,0]
v896 : Path [~6,0]
v897 : Path [~7,0]
link to closure of v489 : Path [0,0]

Closure: v3018 v3037 v3045 v3052
v850 : Path [~1,0]
v980 : Path [~5,0]
v981 : Path [~6,0]
link to closure of v489 : Path [0,0]

Closure: v3225
link to closure of v489 : Path [0,0]

Closure: v2971 v2993
v850 : Path [~1,0]
v1006 : Path [~7,0]
link to closure of v489 : Path [0,0]

Closure: v3226
link to closure of v489 : Path [0,0]

Closure: v3227
link to closure of v489 : Path [0,0]

Closure: v3228
link to closure of v489 : Path [0,0]

Closure: v3229
link to closure of v489 : Path [0,0]

Closure: v3230
link to closure of v489 : Path [0,0]

Closure: v3231
link to closure of v489 : Path [0,0]

Closure: v3232
link to closure of v489 : Path [0,0]

Closure: v3233
link to closure of v489 : Path [0,0]

Closure: v3234
link to closure of v489 : Path [0,0]

Closure: v3235
link to closure of v489 : Path [0,0]

Closure: v3236
link to closure of v489 : Path [0,0]

Closure: v3237
link to closure of v489 : Path [0,0]

Closure: v3238
link to closure of v489 : Path [0,0]

Closure: v3239
link to closure of v489 : Path [0,0]

Closure: v3240
link to closure of v489 : Path [0,0]

Closure: v3241
link to closure of v489 : Path [0,0]

Closure: v3242
link to closure of v489 : Path [0,0]

Closure: v3243
link to closure of v489 : Path [0,0]

Closure: v3244
link to closure of v489 : Path [0,0]

Closure: v3245
link to closure of v489 : Path [0,0]

Closure: v3246
link to closure of v489 : Path [0,0]

Closure: v3247
link to closure of v489 : Path [0,0]

Closure: v3248
link to closure of v489 : Path [0,0]

Closure: v3249
link to closure of v489 : Path [0,0]

Closure: v3250
link to closure of v489 : Path [0,0]

Closure: v3251
link to closure of v489 : Path [0,0]

Closure: v3252
link to closure of v489 : Path [0,0]

Closure: v3253
link to closure of v489 : Path [0,0]

Closure: v3254
link to closure of v489 : Path [0,0]

Closure: v3255
link to closure of v489 : Path [0,0]

Closure: v3256
link to closure of v489 : Path [0,0]

Closure: v3257
link to closure of v489 : Path [0,0]

Closure: v3258
link to closure of v489 : Path [0,0]

Closure: v3259
link to closure of v489 : Path [0,0]

Closure: v2955
v850 : Path [~1,0]
v1037 : Path [~8,0]
v1038 : Path [~9,0]
link to closure of v489 : Path [0,0]

Closure: v3260
link to closure of v489 : Path [0,0]

Closure: v2861 v2877 v2892 v2903 v2915 v2935 v2942
v850 : Path [~1,0]
v1037 : Path [~8,0]
v1038 : Path [~9,0]
link to closure of v489 : Path [0,0]

Closure: v2856
link to closure of v489 : Path [0,0]

Closure: v2852
link to closure of v489 : Path [0,0]

Closure: v2836
v894 : Path [~4,0]
v2844 : Path [~16,0]
v2845 : Path [~15,0]
v2846 : Path [~14,0]
v2847 : Path [~13,0]
v2848 : Path [~12,0]
v2849 : Path [~11,0]
v2850 : Path [~10,0]
link to closure of v489 : Path [0,0]

Closure: v2829
v850 : Path [~1,0]
link to closure of v489 : Path [0,0]

Closure: v2780 v2807 v2810
v1113 : Path [~9,0]
v2813 : Path [~15,0]
v2814 : Path [~14,0]
v2815 : Path [~13,0]
v2821 : Path [~12,0]
v2829 : Path [~11,0]
link to closure of v489 : Path [0,0]

Closure: v2755 v2767
v850 : Path [~1,0]
v1036 : Path [~7,0]
v2779 : Known
v2807 : Path [~16,1]
v2810 : Path [~16,2]
v2829 : Path [~11,0]
link to closure of v489 : Path [0,0]

Closure: v2361 v2389 v2402 v2416 v2429 v2443 v2497 v2511 v2567 v2604 v2625 v2654 v2680 v2710 v2725 v2741 v1202 v1249
v850 : Path [~1,0]
v894 : Path [~4,0]
v980 : Path [~5,0]
v1036 : Path [~7,0]
v1123 : Path [~10,0]
v2779 : Known
v2780 : Path [~16,0]
v2807 : Path [~16,1]
v2810 : Path [~16,2]
v2813 : Path [~15,0]
v2814 : Path [~14,0]
link to closure of v489 : Path [0,0]

Closure: v2360
link to closure of v489 : Path [0,0]

Closure: v2357
link to closure of v489 : Path [0,0]

Closure: v2349 v2352
v2355 : Path [~22,0]
v2358 : Path [~21,0]
link to closure of v489 : Path [0,0]

Closure: v1318
link to closure of v489 : Path [0,0]

Closure: v2296 v2325 v2343
v850 : Path [~1,0]
v980 : Path [~5,0]
v1036 : Path [~7,0]
v1113 : Path [~9,0]
v2346 : Path [~24,0]
v2355 : Path [~22,0]
v2358 : Path [~21,0]
v2511 : Path [~20,7]
v2654 : Path [~20,11]
v2680 : Path [~20,12]
v2779 : Known
v2780 : Path [~16,0]
v2813 : Path [~15,0]
v2814 : Path [~14,0]
v2815 : Path [~13,0]
link to closure of v489 : Path [0,0]

Closure: v2290 v2293
link to closure of v489 : Path [0,0]

Closure: v2285
v2289 : Path [~13,0]
v2290 : Path [~12,0]
link to closure of v489 : Path [0,0]

Closure: v2277
link to closure of v489 : Path [0,0]

Closure: v2271
v1362 : Path [~16,0]
link to closure of v489 : Path [0,0]

Closure: v2258 v2267
v1366 : Path [~18,0]
link to closure of v489 : Path [0,0]

Closure: v2187 v2193 v2199 v2205 v2219 v2253
v850 : Path [~1,0]
v980 : Path [~5,0]
v1350 : Path [~12,0]
v2257 : Path [~20,0]
v2258 : Path [~19,0]
link to closure of v489 : Path [0,0]

Closure: v3261
link to closure of v489 : Path [0,0]

Closure: v3262
link to closure of v489 : Path [0,0]

Closure: v2159 v2163 v2170 v2177 v1450
v850 : Path [~1,0]
v1036 : Path [~7,0]
v1423 : Path [~14,0]
link to closure of v489 : Path [0,0]

Closure: v2149
v1450 : Path [~15,4]
v2153 : Path [~16,0]
link to closure of v489 : Path [0,0]

Closure: v3263
link to closure of v489 : Path [0,0]

Closure: v3264
link to closure of v489 : Path [0,0]

Closure: v3265
link to closure of v489 : Path [0,0]

Closure: v3266
link to closure of v489 : Path [0,0]

Closure: v3267
link to closure of v489 : Path [0,0]

Closure: v3268
link to closure of v489 : Path [0,0]

Closure: v3269
link to closure of v489 : Path [0,0]

Closure: v3270
link to closure of v489 : Path [0,0]

Closure: v3271
link to closure of v489 : Path [0,0]

Closure: v2020 v2137 v1477
v1036 : Path [~7,0]
v1456 : Path [~14,0]
v2141 : Known
v2142 : Known
v2143 : Known
v2144 : Path [~17,0]
link to closure of v489 : Path [0,0]

Closure: v2015
v2019 : Path [~19,0]
v2020 : Path [~18,0]
link to closure of v489 : Path [0,0]

Closure: v3273
link to closure of v489 : Path [0,0]

Closure: v3274
link to closure of v489 : Path [0,0]

Closure: v3275
link to closure of v489 : Path [0,0]

Closure: v3276
link to closure of v489 : Path [0,0]

Closure: v3277
link to closure of v489 : Path [0,0]

Closure: v3278
link to closure of v489 : Path [0,0]

Closure: v3279
link to closure of v489 : Path [0,0]

Closure: v3280
link to closure of v489 : Path [0,0]

Closure: v3281
link to closure of v489 : Path [0,0]

Closure: v1886 v1907 v1923 v1957
v850 : Path [~1,0]
v1036 : Path [~7,0]
v1456 : Path [~14,0]
link to closure of v489 : Path [0,0]

Closure: v1850 v1880
v894 : Path [~4,0]
v980 : Path [~5,0]
v1123 : Path [~10,0]
v1341 : Path [~11,0]
v1456 : Path [~14,0]
v1632 : Path [~18,0]
link to closure of v489 : Path [0,0]

Closure: v1840
v1653 : Path [~27,0]
link to closure of v489 : Path [0,0]

Closure: v1657
link to closure of v489 : Path [0,0]

Closure: v1659
link to closure of v489 : Path [0,0]

Closure: v1829
v1653 : Path [~27,0]
link to closure of v489 : Path [0,0]

Closure: v1670
link to closure of v489 : Path [0,0]

Closure: v1809
v1456 : Path [~14,0]
v1670 : Path [~33,0]
link to closure of v489 : Path [0,0]

Closure: v1783 v1789
link to closure of v489 : Path [0,0]

Closure: v1778 v1780
v850 : Path [~1,0]
v1036 : Path [~7,0]
v1782 : Known
link to closure of v489 : Path [0,0]

Closure: v1729
v1456 : Path [~14,0]
v1678 : Path [~16,0]
v1696 : Path [~17,0]
link to closure of v489 : Path [0,0]

Closure: v3282
link to closure of v489 : Path [0,0]

Closure: v3283
link to closure of v489 : Path [0,0]

Closure: v3284
link to closure of v489 : Path [0,0]

Closure: v3285
link to closure of v489 : Path [0,0]

Closure: v1748 v1755
v1729 : Path [~8,0]
v1763 : Path [~3,0]
v1769 : Path [~4,0]
v1770 : Path [0,0]

Closure: v1720
v1729 : Path [0,~1]

Closure: v1725
v1763 : Path [0,0]

Closure: v1683
v1792 : Path [~3,0]
v1793 : Path [~4,0]
link to closure of v1783 : Path [0,~1]

Closure: v1872
link to closure of v1850 : Path [0,0]

Closure: v2063 v2105 v1525 v1533
v1477 : Path [~4,0]
v2129 : Path [~3,0]
v2130 : Path [0,0]

Closure: v1490
v2129 : Path [0,~1]

Closure: v2065 v1506
v2129 : Path [0,0]

Closure: v1510
v2129 : Path [0,0]

Closure: v2246
link to closure of v2187 : Path [0,~4]

Closure: v1384
link to closure of v2187 : Path [0,~4]

Closure: v1395
v2243 : Path [~4,0]
v2258 : Path [0,~4]

Closure: v1393
v2236 : Path [~4,0]
v2238 : Path [~5,0]
v2243 : Path [0,0]

Closure: v1405
v2210 : Path [~7,0]
v2212 : Path [~6,0]
v2213 : Path [~5,0]
v2215 : Path [~3,0]
v2216 : Path [~4,0]
v2258 : Path [0,~3]

Closure: v1357
v1354 : Path [~1,0]
v2281 : Path [~3,0]
link to closure of v2277 : Path [0,0]

Closure: v2327 v2334
v850 : Path [0,~1]

Closure: v2308
v1113 : Path [~6,0]
v2318 : Path [~4,0]
v2322 : Path [0,0]

Closure: v2307
link to closure of v2296 : Path [0,0]

Closure: v2305
link to closure of v2296 : Path [0,0]

Closure: v1338
link to closure of v2296 : Path [0,0]

Closure: v2302
link to closure of v2296 : Path [0,0]

Closure: v1247
v1036 : Path [~8,0]
v1249 : Path [~3,0]
v2554 : Path [~5,0]
v2557 : Path [~6,0]
v2560 : Path [~1,0]
v2561 : Path [0,~17]

Closure: v2686
v2700 : Path [~4,0]
link to closure of v2361 : Path [0,~12]

Closure: v2660
v2673 : Path [~4,0]
link to closure of v2361 : Path [0,~11]

Closure: v1216 v1219
v2616 : Path [~7,0]
v2617 : Path [~6,0]
v2619 : Path [~3,0]
link to closure of v2361 : Path [0,~9]

Closure: v1236
v850 : Path [~1,0]
v894 : Path [~3,0]
v1036 : Path [~4,0]
v2593 : Path [~5,0]
v2596 : Path [~6,0]
v2597 : Path [~7,0]
v2598 : Path [0,~8]

Closure: v2512
v850 : Path [~1,0]
v894 : Path [~3,0]
v2537 : Path [~4,0]
v2540 : Path [~5,0]
v2541 : Path [~6,0]
v2542 : Path [~7,0]
v2543 : Path [0,~7]

Closure: v1261
v894 : Path [~1,0]
v1257 : Path [~4,0]
v2530 : Path [~3,0]
v2534 : Path [0,0]

Closure: v2452 v2462
v850 : Path [0,~5]

Closure: v2377
link to closure of v2361 : Path [0,0]

Closure: v2368
link to closure of v2361 : Path [0,0]

Closure: v1154
v1153 : Path [~1,0]
link to closure of v2755 : Path [0,0]

Closure: v1064
v2923 : Path [~6,0]
v2929 : Path [~3,0]
v2930 : Path [~4,0]
v2931 : Path [~5,0]
link to closure of v2861 : Path [0,~4]

Closure: v1076
v1075 : Path [~1,0]
link to closure of v2861 : Path [0,~3]

Closure: v1072
v1075 : Path [~1,0]
v1076 : Path [~3,0]
v2908 : Path [0,0]

Closure: v1084
v1083 : Path [~1,0]
link to closure of v2861 : Path [0,~2]

Closure: v1080
v1083 : Path [~1,0]
v1084 : Path [0,0]

Closure: v1094
v1093 : Path [~1,0]
link to closure of v2861 : Path [0,~1]

Closure: v1095
v1094 : Path [~1,0]
link to closure of v1093 : Path [0,0]

Closure: v1090
v1093 : Path [0,0]

Closure: v1106
v1105 : Path [~1,0]
link to closure of v2861 : Path [0,0]

Closure: v1107
v1106 : Path [~1,0]
link to closure of v1105 : Path [0,0]

Closure: v1102
v1105 : Path [~3,0]
v1106 : Path [0,0]

Closure: v1043
v2961 : Path [~5,0]
v2967 : Path [~3,0]
v2968 : Path [~4,0]
link to closure of v2955 : Path [0,0]

Closure: v1017
v3004 : Path [~6,0]
v3009 : Path [~3,0]
v3010 : Path [~4,0]
v3011 : Path [~5,0]
link to closure of v2971 : Path [0,~1]

Closure: v1029 v1032
v2984 : Path [~7,0]
v2985 : Path [~6,0]
v2986 : Path [~5,0]
v2988 : Path [~3,0]
v2989 : Path [~4,0]
link to closure of v2971 : Path [0,0]

Closure: v1001
v3030 : Path [~5,0]
v3037 : Path [0,0]

Closure: v923
link to closure of v3060 : Path [0,~6]

Closure: v930
v927 : Path [~1,0]
link to closure of v3060 : Path [0,~5]

Closure: v939
v934 : Path [~1,0]
link to closure of v3060 : Path [0,~4]

Closure: v935
link to closure of v939 : Path [0,0]

Closure: v938
v3121 : Path [~3,0]
v3122 : Path [~4,0]
link to closure of v939 : Path [0,0]

Closure: v948
v943 : Path [~1,0]
link to closure of v3060 : Path [0,~3]

Closure: v944
link to closure of v948 : Path [0,0]

Closure: v947
v3110 : Path [~3,0]
v3111 : Path [~4,0]
link to closure of v948 : Path [0,0]

Closure: v955
v952 : Path [~1,0]
link to closure of v3060 : Path [0,~2]

Closure: v962
v959 : Path [~1,0]
link to closure of v3060 : Path [0,~1]

Closure: v976
v973 : Path [~1,0]
link to closure of v3060 : Path [0,0]
[closing boot/perv.sml]
[Loading boot/assembly.sml]
structure Dummy
structure Initial
[closing boot/assembly.sml]
[Loading boot/overloads.sml]
structure Overloads
[closing boot/overloads.sml]
hello there
[globalhandle := false]
[dumpCore := true]
[Compiling boot/loader.sml]
signature Startup
functor Loader

Closure: v3444

Closure: v3354
v3325 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v3417 v3423 v3426 v3380
v3325 : Path [~5,0]
v3357 : Path [~4,0]
v3439 : Path [~3,0]
v3441 : Path [0,0]

Closure: v3362
v3325 : Path [~1,0]
v3357 : Path [0,~2]
[closing boot/loader.sml]
[Compiling util/errormsg.sml]
signature ERRORMSG
structure ErrorMsg

Closure: v3544

Closure: v3488 v3501 v3510 v3513 v3517 v3522 v3525
v3325 : Path [~3,0]
v3458 : Path [~4,0]
v3538 : Path [~8,0]
v3539 : Path [~7,0]
v3540 : Path [~6,0]
v3541 : Path [~5,0]
BOGUS : Path [0,0]
[closing util/errormsg.sml]
[Compiling util/dynamic.sml]
signature STATIC_ARRAY
signature DYNAMIC_ARRAY
functor Dynamic

Closure: v3624

Closure: v3552
v3325 : Path [~5,0]
v3487 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v3603 v3616 v3575
v3325 : Path [~1,0]
v3487 : Path [~3,0]
v3552 : Path [0,0]

Closure: v3573
v3552 : Path [~13,0]
v3586 : Path [~8,0]
v3600 : Path [0,~2]
[closing util/dynamic.sml]
[Compiling util/sort.sml]
structure Sort

Closure: v3727

Closure: v3667 v3681
v3628 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v3636 v3642 v3649
v3628 : Path [~1,0]
v3629 : Path [0,~1]

Closure: v3683
v3642 : Path [~3,1]
v3649 : Path [~3,2]
link to closure of v3667 : Path [0,~1]

Closure: v3662
v3657 : Path [~1,0]
link to closure of v3667 : Path [0,0]
[closing util/sort.sml]
[Compiling util/binsort.sml]
structure BinSort

Closure: v3804

Closure: v3778 v3799
v3325 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v3755
v3325 : Path [~3,0]
v3742 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v3750
v3325 : Path [~1,0]
v3742 : Path [0,0]

Closure: v3741
v3740 : Path [~1,0]
link to closure of v3778 : Path [0,0]

Closure: v3737
v3325 : Path [~1,0]
v3741 : Path [~3,0]
v3793 : Path [0,0]
[closing util/binsort.sml]
[Compiling util/list2.sml]
structure List2

Closure: v3889

Closure: v3812 v3822 v3832
BOGUS : Path [0,0]

Closure: v3834
v3854 : Path [~1,0]
link to closure of v3812 : Path [0,~2]

Closure: v3824
v3870 : Path [~1,0]
link to closure of v3812 : Path [0,~1]

Closure: v3814
v3887 : Path [~1,0]
link to closure of v3812 : Path [0,0]
[closing util/list2.sml]
[Compiling util/intset.sml]
structure Intset

Closure: v3957

Closure: v3920 v3935 v3943 v3951
v3325 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v3902
v3901 : Path [~1,0]
link to closure of v3920 : Path [0,~2]

Closure: v3908
v3907 : Path [~1,0]
link to closure of v3920 : Path [0,~1]

Closure: v3905
v3908 : Path [~1,0]
link to closure of v3907 : Path [0,0]

Closure: v3918
v3917 : Path [~1,0]
link to closure of v3920 : Path [0,0]

Closure: v3913
v3918 : Path [~1,0]
link to closure of v3917 : Path [0,0]
[closing util/intset.sml]
[Compiling util/intmap.sml]
structure Intmap

Closure: v4066

Closure: v4006 v4017 v4034 v4050 v4060
v3325 : Path [~3,0]
v3964 : Path [~4,0]
BOGUS : Path [0,0]

Closure: v3973
v3972 : Path [~1,0]
link to closure of v4006 : Path [0,~3]

Closure: v3983
v3982 : Path [~1,0]
link to closure of v4006 : Path [0,~2]

Closure: v3979
v3964 : Path [~1,0]
v3983 : Path [0,0]

Closure: v3995
v3994 : Path [~1,0]
link to closure of v4006 : Path [0,~1]

Closure: v3990
v3995 : Path [~1,0]
link to closure of v3994 : Path [0,0]

Closure: v4004
v4003 : Path [~1,0]
link to closure of v4006 : Path [0,0]

Closure: v4000
v3325 : Path [~1,0]
v4003 : Path [0,0]
[closing util/intmap.sml]
[Compiling util/topsort.sml]
structure Topsort

Closure: v4158

Closure: v4133
v3325 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v4106
v3325 : Path [~3,0]
v4084 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v4104
v4103 : Path [~1,0]
link to closure of v4106 : Path [0,0]

Closure: v4100
v3325 : Path [0,0]

Closure: v4098
v3325 : Path [~3,0]
v4084 : Path [0,0]

Closure: v4095
v4117 : Path [~7,0]
link to closure of v4098 : Path [0,0]

Closure: v4080
v3325 : Path [~1,0]
v4067 : Path [0,0]

Closure: v4078
v3325 : Path [~3,0]
v4067 : Path [0,0]
[closing util/topsort.sml]
[Compiling util/union.sml]
signature UNIONFIND
structure Unionfind

Closure: v4225

Closure: v4179
v4005 : Path [~3,0]
v4160 : Path [~4,0]
BOGUS : Path [0,0]

Closure: v4182 v4166
v4005 : Path [~1,0]
v4160 : Path [~4,0]
v4161 : Path [~3,0]
v4219 : Path [0,0]
signature SIBLINGS
structure Siblings

Closure: v4341

Closure: v4271
v4005 : Path [~5,0]
v4178 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v4276 v4294 v4305 v4316 v4263
v4005 : Path [~8,0]
v4329 : Path [~7,0]
v4330 : Path [~4,0]
v4333 : Path [~5,0]
v4334 : Path [0,0]

Closure: v4259
v4263 : Path [~4,0]
v4291 : Path [0,~4]
[closing util/union.sml]
[Compiling basics/token.sml]
signature TOKEN
structure Token

Closure: v4354

Closure: v4348
BOGUS : Path [0,0]
[closing basics/token.sml]
[Compiling basics/symbol.sml]
signature SYMBOL
structure Symbol

Closure: v4408

Closure: v4374 v4381 v4388 v4393
v3325 : Path [~3,0]
v4405 : Path [~4,0]
BOGUS : Path [0,0]
[closing basics/symbol.sml]
[Compiling util/printutil.sml]
signature PRINTUTIL
structure PrintUtil

Closure: v4569

Closure: v4513 v4518 v4533 v4557 v4561 v4424
v3325 : Path [~5,0]
v4373 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v4508
v3325 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v4476 v4492 v4495
v3325 : Path [~5,0]
v4503 : Path [~11,0]
v4504 : Path [~10,0]
v4505 : Path [~9,0]
v4508 : Path [~8,0]
v4512 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v4471
v3325 : Path [~1,0]
v4467 : Path [~3,0]
v4489 : Path [0,0]

Closure: v4436
v4435 : Path [~1,0]
link to closure of v4513 : Path [0,~2]

Closure: v4437
v4436 : Path [~1,0]
link to closure of v4435 : Path [0,0]

Closure: v4432
v4435 : Path [0,0]

Closure: v4445
v4444 : Path [~1,0]
link to closure of v4513 : Path [0,~1]

Closure: v4446
v4445 : Path [~1,0]
link to closure of v4444 : Path [0,0]
[closing util/printutil.sml]
[Compiling lex/ascii.sml]
structure Ascii

Closure: v4693

Closure: v4628 v4634 v4640
v3325 : Path [~3,0]
BOGUS : Path [0,0]
[closing lex/ascii.sml]
[Compiling lex/symbols.sml]
signature SYMBOLS
structure Symbols

Closure: v4902

Closure: v4822 v4836 v4854 v4866 v4880
v3325 : Path [~7,0]
v4373 : Path [~3,0]
v4699 : Path [~8,0]
v4895 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v4809 v4815
v3325 : Path [~7,0]
v4373 : Path [~3,0]
v4821 : Path [~11,0]
v4822 : Path [~10,0]
BOGUS : Path [0,0]

Closure: v4707
v3325 : Path [~3,0]
v4699 : Path [~4,0]
v4888 : Path [~5,0]
v4889 : Path [0,~4]

Closure: v4715
v3325 : Path [~6,0]
v4699 : Path [~5,0]
v4872 : Path [~3,0]
v4873 : Path [~4,0]
v4875 : Path [0,~3]

Closure: v4722
v3325 : Path [~1,0]
v4718 : Path [~5,0]
v4860 : Path [~4,0]
v4861 : Path [~3,0]
v4862 : Path [0,~2]

Closure: v4732
v3325 : Path [~6,0]
v4373 : Path [~5,0]
v4699 : Path [~3,0]
v4846 : Path [~4,0]
v4847 : Path [0,~1]

Closure: v4741
v3325 : Path [~1,0]
v4373 : Path [~3,0]
v4736 : Path [0,0]
[closing lex/symbols.sml]
[Compiling lex/charbuff.sml]
signature CHAR_BUFFER
structure CharBuffer

Closure: v4986

Closure: v4937 v4942 v4945 v4963 v4968 v4973
v3325 : Path [~11,0]
v3487 : Path [~7,0]
v4627 : Path [~9,0]
v4753 : Path [~5,0]
v4912 : Path [~12,0]
v4913 : Path [~13,0]
v4977 : Path [~15,0]
v4979 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v4928
v3325 : Path [~6,0]
v4627 : Path [~4,0]
v4955 : Path [0,~2]
[closing lex/charbuff.sml]
[Compiling lex/lex.sml]
signature LEX
structure Lex

Closure: v5522

Closure: v5475 v5482
v3325 : Path [~13,0]
v4627 : Path [~9,0]
v5494 : Path [~23,0]
v5496 : Path [~21,0]
BOGUS : Path [0,0]

Closure: v5438
v3325 : Path [~13,0]
v3487 : Path [~11,0]
v4627 : Path [~9,0]
v4936 : Path [~7,0]
v5032 : Path [~29,0]
v5482 : Path [~28,1]
v5494 : Path [~23,0]
BOGUS : Path [0,0]

Closure: v5435 v5042 v5044 v5046 v5048 v5050 v5052 v5054 v5057 v5059 v5061 v5063 v5065 v5067 v5070 v5072 v5074 v5078 v5080 v5082 v5084 v5086 v5088 v5090 v5092 v5094 v5097 v5099 v5101 v5103 v5105 v5107
v3325 : Path [~13,0]
v3487 : Path [~11,0]
v4627 : Path [~9,0]
v4753 : Path [~15,0]
v4936 : Path [~7,0]
v5037 : Path [~31,0]
v5438 : Path [~30,0]
v5482 : Path [~28,1]
v5490 : Path [~27,0]
v5492 : Path [~25,0]
v5494 : Path [~23,0]
v5495 : Path [~22,0]
v5497 : Path [~20,0]
v5498 : Path [~19,0]
v5499 : Path [~18,0]
v5500 : Path [~17,0]
v5501 : Path [~16,0]
BOGUS : Path [0,0]

Closure: v5252 v5262 v5272 v5275 v5158
v3325 : Path [~13,0]
v3487 : Path [~11,0]
v4347 : Path [~3,0]
v4753 : Path [~15,0]
v5037 : Path [~31,0]
v5284 : Path [~50,0]
v5493 : Path [~24,0]
v5494 : Path [~23,0]
v5499 : Path [~18,0]
BOGUS : Path [0,0]

Closure: v5193 v5203 v5216 v5233
v3325 : Path [~13,0]
v3487 : Path [~11,0]
v4627 : Path [~9,0]
v5243 : Path [~53,0]
v5244 : Path [~52,0]
v5490 : Path [~27,0]
v5491 : Path [~26,0]
v5492 : Path [~25,0]
v5493 : Path [~24,0]
v5494 : Path [~23,0]
v5495 : Path [~22,0]
v5496 : Path [~21,0]
BOGUS : Path [0,0]

Closure: v5268
link to closure of v5252 : Path [0,~1]

Closure: v5258
link to closure of v5252 : Path [0,0]

Closure: v5034
v3325 : Path [0,0]

Closure: v5029
v3325 : Path [0,0]
[closing lex/lex.sml]
[Compiling basics/table.sml]
signature TABLE
structure Table
basics/table.sml, line 75: Warning: binding not exhaustive
        x :: b = ...

Closure: v5689

Closure: v5594 v5600 v5619 v5631 v5643 v5650 v5671 v5682
v3325 : Path [~5,0]
v4373 : Path [~3,0]
v5536 : Path [~6,0]
v5537 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v5557
v5556 : Path [~1,0]
link to closure of v5594 : Path [0,~5]

Closure: v5553
v4373 : Path [~4,0]
v5536 : Path [0,0]

Closure: v5572
v3325 : Path [~3,0]
v5627 : Path [~4,0]
v5628 : Path [0,~2]

Closure: v5580 v5583
v3325 : Path [~3,0]
v5615 : Path [~4,0]
v5616 : Path [0,~1]

Closure: v5589
v3325 : Path [~1,0]
v5587 : Path [0,0]
[closing basics/table.sml]
[Compiling basics/access.sig]
signature ACCESS
[closing basics/access.sig]
[Compiling basics/access.sml]
structure Access

Closure: v5757

Closure: v5724 v5728 v5732 v5739 v5742
v3325 : Path [~7,0]
v4373 : Path [~3,0]
v5705 : Path [~8,0]
v5746 : Path [~11,0]
v5747 : Path [~10,0]
v5748 : Path [~9,0]
BOGUS : Path [0,0]
[closing basics/access.sml]
[Compiling basics/basics.sig]
signature BASICS
[closing basics/basics.sig]
[Compiling basics/basics.sml]
structure Basics

Closure: v5941

Closure: v5909 v5913 v5920 v5923 v5926
v5723 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v5897 v5900 v5903
v3325 : Path [~9,0]
v5906 : Path [~16,0]
v5907 : Path [~15,0]
v5908 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v5942
BOGUS : Path [0,0]

Closure: v5834 v5850 v5864 v5880
v5897 : Path [~17,0]
v5900 : Path [~17,1]
BOGUS : Path [0,0]
[closing basics/basics.sml]
[Compiling basics/tuples.sig]
signature TUPLES
[closing basics/tuples.sig]
[Compiling basics/tuples.sml]
structure Tuples

Closure: v6076

Closure: v6056
v3325 : Path [~9,0]
v4753 : Path [~7,0]
v5833 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v6041 v6047
v3325 : Path [~9,0]
v4753 : Path [~7,0]
v5955 : Path [~10,0]
v6055 : Path [~13,0]
BOGUS : Path [0,0]

Closure: v6024 v6031
v3325 : Path [~9,0]
v5833 : Path [~3,0]
v5961 : Path [~11,0]
v6040 : Path [~16,0]
v6041 : Path [~15,0]
v6054 : Path [~14,0]
v6056 : Path [~12,0]
BOGUS : Path [0,0]

Closure: v6001 v5995
v5833 : Path [~3,0]
v6047 : Path [~15,1]
BOGUS : Path [0,0]

Closure: v5977
v5975 : Path [~1,0]
v6047 : Path [0,0]

Closure: v6057
v3325 : Path [0,0]
[closing basics/tuples.sml]
[Compiling basics/basictypes.sig]
signature BASICTYPES
[closing basics/basictypes.sig]
[Compiling basics/basictypes.sml]
structure BasicTypes

Closure: v6248

Closure: v6222
v6228 : Path [~24,0]
BOGUS : Path [0,0]

Closure: v6197 v6201
v3325 : Path [~9,0]
v6000 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v6202
link to closure of v6197 : Path [0,~1]

Closure: v6206
link to closure of v6197 : Path [0,~1]
[closing basics/basictypes.sml]
[Compiling basics/printtype.sml]
signature PRINTTYPE
structure PrintType
basics/printtype.sml, line 140: Warning: binding not exhaustive
        domain :: range :: nil = ...
basics/printtype.sml, line 140: Warning: binding not exhaustive
        TYCON {stamp=arrowStamp,...} = ...

Closure: v6551

Closure: v6539
v3325 : Path [~11,0]
BOGUS : Path [0,0]

Closure: v6262
v3325 : Path [~11,0]
v6538 : Path [~17,0]
v6539 : Path [~16,0]
BOGUS : Path [0,0]

Closure: v6523
v3325 : Path [~11,0]
v6530 : Path [~17,0]
BOGUS : Path [0,0]

Closure: v6501 v6505
v3325 : Path [~11,0]
v6521 : Path [~20,0]
v6522 : Path [~19,0]
v6530 : Path [~17,0]
BOGUS : Path [0,0]

Closure: v6452 v6477 v6483
v3325 : Path [~11,0]
v4475 : Path [~13,0]
v6500 : Path [~22,0]
v6505 : Path [~21,1]
v6530 : Path [~17,0]
BOGUS : Path [0,0]

Closure: v6315 v6318 v6320 v6323 v6329 v6333
v3325 : Path [~11,0]
v3487 : Path [~7,0]
v3835 : Path [~9,0]
v4475 : Path [~13,0]
v6000 : Path [~15,0]
v6450 : Path [~26,0]
v6452 : Path [~23,0]
v6483 : Path [~23,2]
BOGUS : Path [0,0]

Closure: v6332
link to closure of v6315 : Path [0,~5]

Closure: v6328
link to closure of v6315 : Path [0,~4]

Closure: v6297
link to closure of v6452 : Path [0,0]

Closure: v6276
v3325 : Path [~1,0]
v6272 : Path [0,~1]

Closure: v6266
v3325 : Path [~1,0]
v6264 : Path [0,0]
[closing basics/printtype.sml]
[Compiling basics/typesutil.sig]
signature TYPESUTIL
[closing basics/typesutil.sig]
[Compiling basics/typesutil.sml]
structure TypesUtil
basics/typesutil.sml, line 356: Warning: binding not exhaustive
        ty2 :: argTys' = ...
basics/typesutil.sml, line 356: Warning: binding not exhaustive
        STRstr {env=env,...} = ...

Closure: v7588

Closure: v7398 v7411 v7436 v7459 v7484 v7490 v7509 v7528 v7555 v7574 v6619 v6645
v3325 : Path [~11,0]
v3487 : Path [~7,0]
v4475 : Path [~9,0]
v5833 : Path [~3,0]
v6574 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v7356 v6664
v3325 : Path [~11,0]
v6659 : Path [~16,0]
BOGUS : Path [0,0]

Closure: v7184 v7254 v7339 v6689 v6704 v6708
v3325 : Path [~11,0]
v3487 : Path [~7,0]
v3835 : Path [~5,0]
v5833 : Path [~3,0]
v6154 : Path [~13,0]
v6645 : Path [~15,11]
v6679 : Path [~18,0]
v7356 : Path [~17,0]
v7411 : Path [~15,1]
v7484 : Path [~15,4]
BOGUS : Path [0,0]

Closure: v7177
v3325 : Path [~11,0]
v5833 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v6841 v7107 v6789 v6800 v6825 v6830
v3325 : Path [~11,0]
v3487 : Path [~7,0]
v4475 : Path [~9,0]
v6645 : Path [~15,11]
v6679 : Path [~18,0]
v6751 : Path [~22,0]
v6752 : Path [~23,0]
v7177 : Path [~21,0]
v7183 : Path [~20,0]
v7339 : Path [~19,2]
v7411 : Path [~15,1]
v7484 : Path [~15,4]
BOGUS : Path [0,0]

Closure: v6763
v3325 : Path [~3,0]
v3487 : Path [0,~1]

Closure: v6774
v3325 : Path [~6,0]
v3487 : Path [~3,0]
v6751 : Path [~5,0]
v7166 : Path [0,~1]

Closure: v7139
link to closure of v6774 : Path [0,0]

Closure: v7111
link to closure of v6763 : Path [0,0]

Closure: v6837
v6847 : Path [~3,0]
link to closure of v6841 : Path [0,0]

Closure: v7266
v3325 : Path [0,~4]

Closure: v7227 v7236 v6739
v3325 : Path [~7,0]
v3487 : Path [0,0]

Closure: v6721
v3325 : Path [~1,0]
v6719 : Path [0,~1]

Closure: v6666
v7397 : Path [~1,0]
link to closure of v7356 : Path [0,~1]

Closure: v6675
v3325 : Path [~4,0]
v6659 : Path [0,0]

Closure: v6576
link to closure of v7398 : Path [0,~9]

Closure: v7460
v6621 : Path [~1,0]
link to closure of v7398 : Path [0,~3]

Closure: v6634
v3325 : Path [~5,0]
v7451 : Path [0,~2]

Closure: v6655
v3325 : Path [0,0]
[closing basics/typesutil.sml]
[Compiling basics/printbas.sml]
structure PrintBasics

Closure: v7886

Closure: v7678 v7709 v7717 v7746 v7759 v7764 v7783 v7800 v7812 v7824 v7837 v7849 v7606
v3325 : Path [~9,0]
v3487 : Path [~5,0]
v4475 : Path [~11,0]
v5833 : Path [~3,0]
v6340 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v7711
link to closure of v7678 : Path [0,~1]

Closure: v7683
v3325 : Path [~8,0]
v4475 : Path [0,0]

Closure: v7671
v3325 : Path [0,0]
[closing basics/printbas.sml]
[Compiling basics/conrep.sml]
structure ConRep

Closure: v8140

Closure: v7910 v8127
v3325 : Path [~3,0]
v3487 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v7891
v7888 : Path [~1,0]
link to closure of v7910 : Path [0,~1]

Closure: v7966
link to closure of v7910 : Path [0,0]

Closure: v7905
v3487 : Path [~7,0]
v7965 : Path [0,0]

Closure: v8048
link to closure of v7910 : Path [0,0]

Closure: v7985
v3487 : Path [~7,0]
v7983 : Path [0,0]

Closure: v8120
link to closure of v7910 : Path [0,0]

Closure: v8057
v3487 : Path [~3,0]
v8055 : Path [0,0]
[closing basics/conrep.sml]
[Compiling absyn/bareabsyn.sig]
signature BAREABSYN
[closing absyn/bareabsyn.sig]
[Compiling absyn/bareabsyn.sml]
structure BareAbsyn

Closure: v8147
[closing absyn/bareabsyn.sml]
[Compiling absyn/absyn.sml]
structure Absyn

Closure: v8479

Closure: v8453
v6154 : Path [~11,0]
BOGUS : Path [0,0]

Closure: v8264 v8272 v8302 v8369 v8376 v8396 v8402 v8408 v8415 v8422 v8438
v3325 : Path [~15,0]
v3487 : Path [~13,0]
v5723 : Path [~9,0]
v5833 : Path [~3,0]
v6000 : Path [~7,0]
v6154 : Path [~11,0]
v8452 : Path [~30,0]
v8455 : Path [~28,0]
v8456 : Path [~27,0]
v8457 : Path [~26,0]
v8458 : Path [~25,0]
v8459 : Path [~24,0]
v8460 : Path [~23,0]
v8461 : Path [~22,0]
v8462 : Path [~21,0]
v8467 : Path [~20,0]
v8468 : Path [~19,0]
BOGUS : Path [0,0]

Closure: v8167
v6000 : Path [0,~10]

Closure: v8175
v6000 : Path [0,~9]

Closure: v8416
link to closure of v8264 : Path [0,~8]

Closure: v8370
link to closure of v8264 : Path [0,~3]

Closure: v8303
v3325 : Path [0,~2]

Closure: v8217
v5833 : Path [0,0]

Closure: v8312 v8322 v8332
v3487 : Path [0,0]

Closure: v8308
link to closure of v8303 : Path [0,0]

Closure: v8277
v3325 : Path [0,~1]

Closure: v8273
v8277 : Path [~3,0]
link to closure of v8264 : Path [0,~1]

Closure: v8279
v8286 : Path [~4,0]
link to closure of v8277 : Path [0,0]
[closing absyn/absyn.sml]
[Compiling env/prim.sml]
structure Prim
env/prim.sml, line 120: Warning: match not exhaustive
        (s' :: rest,n) => ...

Closure: v8625

Closure: v8602 v8609
v5833 : Path [~5,0]
v8616 : Path [~15,0]
v8617 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v8577
v3325 : Path [~11,0]
v5833 : Path [~5,0]
v8583 : Path [~20,0]
v8584 : Path [~19,0]
v8585 : Path [~18,0]
v8617 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v8562
v3325 : Path [~11,0]
v8576 : Path [~22,0]
BOGUS : Path [0,0]

Closure: v8523
v3325 : Path [~11,0]
v8559 : Path [~25,0]
v8562 : Path [~23,0]
BOGUS : Path [0,0]

Closure: v8554
v3325 : Path [~11,0]
v8559 : Path [~25,0]
BOGUS : Path [0,0]

Closure: v8539
v8548 : Path [~33,0]
v8549 : Path [~32,0]
v8552 : Path [~29,0]
v8553 : Path [~28,0]
BOGUS : Path [0,0]

Closure: v8517
v3325 : Path [~1,0]
v8513 : Path [0,0]
[closing env/prim.sml]
[Compiling env/env.sml]
signature BIND
signature ENV
functor EnvFunc
env/env.sml, line 293: Warning: binding not exhaustive
        OPEN s :: _ = ...
env/env.sml, line 293: Warning: binding not exhaustive
        OPEN s :: _ = ...
env/env.sml, line 293: Warning: binding not exhaustive
        OPEN s :: _ = ...

Closure: v9103

Closure: v8642
v3325 : Path [~11,0]
v3487 : Path [~7,0]
v4373 : Path [~5,0]
v4475 : Path [~9,0]
v5593 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v9075 v9079 v9083 v9092
v3325 : Path [0,0]

Closure: v8799 v8839 v8848 v8880 v8912 v8973 v8992 v9020 v9038 v9051 v9059 v9064 v8674 v8680 v8684
v3325 : Path [~1,0]
v3487 : Path [~3,0]
v4373 : Path [~4,0]
v4475 : Path [~10,0]
v5593 : Path [~9,0]
v8642 : Path [~8,0]
v8644 : Path [~7,0]
v8645 : Path [~6,0]
v9070 : Path [~5,0]
v9071 : Path [~5,1]
v9072 : Path [0,0]

Closure: v8786 v8791 v8794
v3325 : Path [~12,0]
v8798 : Path [~11,6]
v8992 : Path [~11,10]
v9059 : Path [~8,0]
v9072 : Path [~7,0]
v9073 : Path [~6,0]
v9074 : Path [0,0]

Closure: v9000 v8698
v3325 : Path [~1,0]
v3487 : Path [0,~6]

Closure: v8725
v3325 : Path [~3,0]
v3487 : Path [~4,0]
v4475 : Path [0,~4]

Closure: v8720
v8936 : Path [~6,0]
link to closure of v8725 : Path [0,0]

Closure: v8741
v3325 : Path [~3,0]
v3487 : Path [~4,0]
v5593 : Path [0,~3]

Closure: v8754
v3325 : Path [~3,0]
v3487 : Path [~5,0]
v4373 : Path [~6,0]
v4475 : Path [0,~2]

Closure: v8763
v8762 : Path [~1,0]
link to closure of v8799 : Path [0,~1]

Closure: v8777
v8776 : Path [~1,0]
link to closure of v8799 : Path [0,0]

Closure: v8773
v3325 : Path [~1,0]
v4475 : Path [~3,0]
v5593 : Path [~4,0]
v8642 : Path [0,0]
structure EnvBind

Closure: v9115
structure Env

Closure: v9121
[closing env/env.sml]
[Compiling env/envaccess.sig]
signature ENVACCESS
[closing env/envaccess.sig]
[Compiling env/envaccess.sml]
structure EnvAccess
env/envaccess.sml, line 703: Warning: binding not exhaustive
        str as STRstr {stamp=stamp,...} = ...
env/envaccess.sml, line 703: Warning: binding not exhaustive
        STRstr {env={s=s,t=t},...} = ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (STRstr {env=env,table=table,...},id,ap) => ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (STRstr {env=env,table=table,...},id,ap) => ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (tv as ref (UBOUND id')) :: resttvs => ...
        nil => ...
env/envaccess.sml, line 703: Warning: binding not exhaustive
        OPENbtv (ref l) = ...
env/envaccess.sml, line 703: Warning: binding not exhaustive
        VARbind (VALvar {vtype=ref ty,...}) = ...
env/envaccess.sml, line 703: Warning: binding not exhaustive
        VARbind v = ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (pl as (varRef as ref <pat>) :: pl',tl) => ...
        (nil,tl) => ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (STRstr {env=env,table=table,...},id,ap) => ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (STRstr {env=env,table=table,...},id,ap) => ...
env/envaccess.sml, line 703: Warning: binding not exhaustive
        ref (UNDEFtyc id) = ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        (STRstr {env=env,table=table,...} : Structure,id : symbol) => ...
env/envaccess.sml, line 703: Warning: match not exhaustive
        STRvar {access=PATH p,binding=STRstr {env=<pat>,table=<pat>,...},...} :: r => ...
        nil => ...

Closure: v10956

Closure: v10882 v10885 v10914 v10917 v10920
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v9117 : Path [~7,0]
v10939 : Path [~31,0]
BOGUS : Path [0,0]

Closure: v10811 v10824 v10848
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v4475 : Path [~17,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10880 : Path [~33,0]
v10940 : Path [~30,0]
BOGUS : Path [0,0]

Closure: v10798 v9239
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10808 : Path [~36,0]
v10810 : Path [~35,0]
v10824 : Path [~34,1]
BOGUS : Path [0,0]

Closure: v10782
v3325 : Path [~27,0]
v10808 : Path [~36,0]
v10810 : Path [~35,0]
BOGUS : Path [0,0]

Closure: v10784
v3325 : Path [~27,0]
v9239 : Path [~37,1]
v10808 : Path [~36,0]
v10810 : Path [~35,0]
BOGUS : Path [0,0]

Closure: v10717 v10734 v10754 v10777
v6840 : Path [~25,0]
v9117 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v10677 v10680 v10684 v10688 v10696 v10713
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10716 : Path [~40,0]
v10754 : Path [~39,2]
BOGUS : Path [0,0]

Closure: v10578 v10589 v10592 v10612 v10615 v10619 v10630 v10649
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v5723 : Path [~3,0]
v5833 : Path [~5,0]
v6840 : Path [~25,0]
v8538 : Path [~9,0]
v9117 : Path [~7,0]
v10674 : Path [~44,0]
v10675 : Path [~43,0]
v10676 : Path [~42,0]
v10754 : Path [~39,2]
v10885 : Path [~32,1]
BOGUS : Path [0,0]

Closure: v10571
v3325 : Path [~27,0]
v10577 : Path [~46,0]
BOGUS : Path [0,0]

Closure: v9358
v3325 : Path [~27,0]
v9117 : Path [~7,0]
v9350 : Path [~48,0]
v10589 : Path [~45,1]
v10615 : Path [~45,4]
BOGUS : Path [0,0]

Closure: v10550
v3325 : Path [~27,0]
v10577 : Path [~46,0]
BOGUS : Path [0,0]

Closure: v9361
v3325 : Path [~27,0]
v9358 : Path [~49,0]
v10577 : Path [~46,0]
BOGUS : Path [0,0]

Closure: v10486 v10509 v10516 v10535 v10544
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v4475 : Path [~17,0]
v4627 : Path [~13,0]
v5833 : Path [~5,0]
v6340 : Path [~11,0]
v9117 : Path [~7,0]
v10940 : Path [~30,0]
BOGUS : Path [0,0]

Closure: v10424 v10427 v10432 v10455 v10463 v10470 v10474 v10480
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v4627 : Path [~13,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10485 : Path [~52,0]
BOGUS : Path [0,0]

Closure: v10413
v3325 : Path [~27,0]
v4753 : Path [~15,0]
v5833 : Path [~5,0]
v10423 : Path [~54,0]
v10424 : Path [~53,0]
BOGUS : Path [0,0]

Closure: v10286 v10289 v10302 v10320 v10342 v10350 v10362 v10374 v10380 v10397 v10400 v10409
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v4475 : Path [~17,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10412 : Path [~56,0]
v10413 : Path [~55,0]
v10754 : Path [~39,2]
v10885 : Path [~32,1]
v10940 : Path [~30,0]
BOGUS : Path [0,0]

Closure: v10255 v10262 v10279 v10282
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10285 : Path [~58,0]
v10320 : Path [~57,3]
BOGUS : Path [0,0]

Closure: v10253
v9117 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v10198 v10212 v10219 v10225 v10234 v10242
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v5833 : Path [~5,0]
v9117 : Path [~7,0]
v10252 : Path [~60,0]
BOGUS : Path [0,0]

Closure: v10189
v9117 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v10179
v9117 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v10169
v9117 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v9958 v10016 v10035 v10045 v10135
v3325 : Path [~27,0]
v3487 : Path [~19,0]
v3754 : Path [~23,0]
v5833 : Path [~5,0]
v6840 : Path [~25,0]
v9117 : Path [~7,0]
v10302 : Path [~57,2]
v10630 : Path [~45,6]
v10734 : Path [~39,1]
BOGUS : Path [0,0]

Closure: v9914
v3754 : Path [~23,0]
v9117 : Path [~7,0]
v10289 : Path [~57,1]
v10619 : Path [~45,5]
v10717 : Path [~39,0]
BOGUS : Path [0,0]

Closure: v9733
v3325 : Path [~27,0]
v3754 : Path [~23,0]
v4005 : Path [~21,0]
v5833 : Path [~5,0]
v6840 : Path [~25,0]
v9117 : Path [~7,0]
v10016 : Path [~65,1]
BOGUS : Path [0,0]

Closure: v9728
v3325 : Path [~27,0]
v10485 : Path [~52,0]
v10577 : Path [~46,0]
BOGUS : Path [0,0]

Closure: v9890
v3325 : Path [0,0]

Closure: v9841 v9684 v9720
v3325 : Path [~1,0]
v3754 : Path [~12,0]
v4005 : Path [~11,0]
v5833 : Path [~10,0]
v6840 : Path [~7,0]
v9117 : Path [~6,0]
v9640 : Path [~5,0]
v9657 : Path [~4,0]
v9887 : Path [~3,0]
v9888 : Path [0,0]

Closure: v9674
v3325 : Path [~3,0]
v6840 : Path [0,0]

Closure: v9667 v9672
v3325 : Path [~3,0]
v6840 : Path [~4,0]
v9657 : Path [~5,0]
v9674 : Path [~6,0]
v9875 : Path [~7,0]
v9876 : Path [0,0]

Closure: v9650
v3325 : Path [~5,0]
v9897 : Path [~3,0]
v9899 : Path [0,0]

Closure: v9633
v3754 : Path [~1,0]
v9117 : Path [~3,0]
v9618 : Path [0,0]

Closure: v9574
v9573 : Path [~1,0]
link to closure of v9958 : Path [0,~2]

Closure: v9613
v3325 : Path [~1,0]
v3754 : Path [~3,0]
v6840 : Path [0,0]

Closure: v10230
link to closure of v10198 : Path [0,~3]

Closure: v9536
v9535 : Path [~1,0]
link to closure of v10198 : Path [0,0]

Closure: v10204
v3325 : Path [~3,0]
v9117 : Path [0,0]

Closure: v10357
link to closure of v10286 : Path [0,~5]

Closure: v10481
v9392 : Path [~1,0]
link to closure of v10424 : Path [0,~7]

Closure: v9393
link to closure of v10424 : Path [0,~7]

Closure: v9415
v3325 : Path [~1,0]
v3487 : Path [0,~2]

Closure: v10537
link to closure of v10486 : Path [0,~3]

Closure: v9375
v3487 : Path [~4,0]
v5833 : Path [0,~2]

Closure: v10501
link to closure of v10486 : Path [0,0]

Closure: v9204
v9203 : Path [~1,0]
link to closure of v10882 : Path [0,~1]

Closure: v9200
v3325 : Path [~1,0]
v9117 : Path [0,0]
[closing env/envaccess.sml]
[Compiling absyn/printabsyn.sml]
signature PRINTABSYN
structure PrintAbsyn

Closure: v12040

Closure: v11949 v11959 v12003 v12024 v11013 v11019 v11049 v11080 v11127 v11192 v11197 v11202 v11207 v11270 v11284
v3325 : Path [~13,0]
v3487 : Path [~7,0]
v4475 : Path [~17,0]
v6000 : Path [~5,0]
v6340 : Path [~15,0]
v7677 : Path [~11,0]
v9727 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v11279
v11303 : Path [~4,0]
v11304 : Path [~5,0]
link to closure of v11949 : Path [0,~14]

Closure: v11452
link to closure of v11949 : Path [0,~13]

Closure: v11265
v11459 : Path [~4,0]
v11460 : Path [~5,0]
link to closure of v11949 : Path [0,~13]

Closure: v11438
link to closure of v11949 : Path [0,~13]

Closure: v11426
v11459 : Path [~4,0]
v11460 : Path [~5,0]
link to closure of v11949 : Path [0,~13]

Closure: v11410
v11459 : Path [~4,0]
v11460 : Path [~5,0]
link to closure of v11949 : Path [0,~13]

Closure: v11393
link to closure of v11949 : Path [0,~13]

Closure: v11366
link to closure of v11949 : Path [0,~13]

Closure: v11336
link to closure of v11949 : Path [0,~13]

Closure: v11215
v11459 : Path [~4,0]
v11460 : Path [~5,0]
link to closure of v11949 : Path [0,~13]

Closure: v11211
v11459 : Path [~4,0]
v11460 : Path [~5,0]
link to closure of v11949 : Path [0,~13]

Closure: v11357
link to link to closure of v11949 : Path [0,0]

Closure: v11603 v11190
v3325 : Path [0,~9]

Closure: v11635
v3325 : Path [~10,0]
v11192 : Path [~9,0]
v11677 : Path [~4,0]
v11678 : Path [~7,0]
v11681 : Path [~8,0]
v11684 : Path [0,0]

Closure: v11122
v11740 : Path [~4,0]
v11741 : Path [~5,0]
link to closure of v11949 : Path [0,~8]

Closure: v11098
v11740 : Path [~4,0]
v11741 : Path [~5,0]
link to closure of v11949 : Path [0,~8]

Closure: v11705
v11740 : Path [~4,0]
v11741 : Path [~5,0]
link to closure of v11949 : Path [0,~8]

Closure: v11699
v11740 : Path [~4,0]
v11741 : Path [~5,0]
link to closure of v11949 : Path [0,~8]

Closure: v11126
v11740 : Path [~4,0]
v11741 : Path [~5,0]
link to closure of v11949 : Path [0,~8]

Closure: v11821
v3325 : Path [~12,0]
v11080 : Path [~11,0]
v11867 : Path [~6,0]
v11868 : Path [~9,0]
v11873 : Path [0,~7]

Closure: v11915
v11925 : Path [~4,0]
link to closure of v11949 : Path [0,~6]

Closure: v11908
v11925 : Path [~4,0]
link to closure of v11949 : Path [0,~6]

Closure: v10991
v4475 : Path [0,~3]

Closure: v11006
v11005 : Path [~1,0]
link to closure of v11949 : Path [0,~2]

Closure: v11007
v11006 : Path [~1,0]
link to closure of v11005 : Path [0,0]

Closure: v11008
v11007 : Path [~1,0]
link to closure of v11006 : Path [0,0]

Closure: v11002
v4475 : Path [0,0]
[closing absyn/printabsyn.sml]
[Compiling typing/overload.sig]
signature OVERLOAD
[closing typing/overload.sig]
[Compiling typing/overload.sml]
structure Overload

Closure: v12384

Closure: v12235 v12351 v12367 v12066
v3325 : Path [~13,0]
v3487 : Path [~9,0]
v6154 : Path [~5,0]
v6840 : Path [~7,0]
v12046 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v12148 v12160 v12212 v12228 v12231
v3325 : Path [~13,0]
v3487 : Path [~9,0]
v4475 : Path [~11,0]
v6840 : Path [~7,0]
v12046 : Path [~14,0]
v12066 : Path [~15,3]
v12106 : Path [~16,0]
v12234 : Path [~17,0]
v12235 : Path [~15,0]
v12351 : Path [~15,1]
v12367 : Path [~15,2]
BOGUS : Path [0,0]

Closure: v12126 v12131
v3487 : Path [~4,0]
v4475 : Path [~7,0]
v6840 : Path [0,~1]

Closure: v12143
v3325 : Path [0,0]

Closure: v12059
v3325 : Path [0,~1]

Closure: v12299 v12096 v12101
v3325 : Path [~5,0]
v6840 : Path [0,0]

Closure: v12080
v3325 : Path [~3,0]
v6840 : Path [0,0]

Closure: v12307
link to closure of v12080 : Path [0,0]
[closing typing/overload.sml]
[Compiling typing/typecheck.sig]
signature TYPECHECK
[closing typing/typecheck.sig]
[Compiling typing/typecheck.sml]
structure Typecheck
typing/typecheck.sml, line 343: Warning: binding not exhaustive
        VALvar {vtype=refty,...} = ...
typing/typecheck.sml, line 343: Warning: binding not exhaustive
        VARpat (VALvar {vtype=refty,...}) = ...

Closure: v13151

Closure: v13133
v3325 : Path [~23,0]
v13136 : Path [~27,0]
BOGUS : Path [0,0]

Closure: v13108 v13117
v3325 : Path [~23,0]
v5833 : Path [~7,0]
v6154 : Path [~13,0]
v6840 : Path [~19,0]
v13131 : Path [~29,0]
BOGUS : Path [0,0]

Closure: v12990 v13029 v12492 v12531 v12534 v12545 v12589
v3325 : Path [~23,0]
v3487 : Path [~15,0]
v4475 : Path [~11,0]
v5833 : Path [~7,0]
v6154 : Path [~13,0]
v6340 : Path [~9,0]
v6840 : Path [~19,0]
v8538 : Path [~21,0]
v11292 : Path [~25,0]
v12147 : Path [~17,0]
v12416 : Path [~31,0]
v13108 : Path [~30,0]
v13117 : Path [~30,1]
v13136 : Path [~27,0]
v13137 : Path [~26,0]
BOGUS : Path [0,0]

Closure: v12595
v3325 : Path [0,~6]

Closure: v12622 v12636 v12669
v3325 : Path [0,~6]

Closure: v12685
v6840 : Path [0,~6]

Closure: v12729
v3325 : Path [~8,0]
v3487 : Path [0,~5]

Closure: v12765
link to closure of v12990 : Path [0,~3]

Closure: v12510
v6154 : Path [0,~3]

Closure: v12901
v12986 : Path [~4,0]
link to closure of v12990 : Path [0,~2]

Closure: v12425
v6840 : Path [0,~1]

Closure: v13068 v13076 v12451
v3325 : Path [~8,0]
v3487 : Path [~9,0]
v6340 : Path [~7,0]
v6840 : Path [~6,0]
v12416 : Path [~4,0]
v12425 : Path [0,~1]

Closure: v12432
v6840 : Path [~1,0]
v12416 : Path [0,~1]

Closure: v12467
v3325 : Path [~4,0]
v13025 : Path [0,0]

Closure: v12991
link to closure of v12467 : Path [0,0]

Closure: v13125
link to closure of v13108 : Path [0,~1]

Closure: v12407
v3325 : Path [0,~1]
[closing typing/typecheck.sml]
[Compiling typing/sharing.sml]
signature SHARING
structure Sharing
typing/sharing.sml, line 194: Warning: binding not exhaustive
        STRstr {stamp=s2,...} = ...
typing/sharing.sml, line 194: Warning: binding not exhaustive
        STRstr {stamp=s1,...} = ...
typing/sharing.sml, line 194: Warning: binding not exhaustive
        str2 as STRstr {stamp=s2,...} = ...
typing/sharing.sml, line 194: Warning: binding not exhaustive
        str1 as STRstr {stamp=s1,...} = ...
typing/sharing.sml, line 194: Warning: binding not exhaustive
        STRstr {env=env,kind=kind,sign=sign,stamp=stamp,table=table} = ...
typing/sharing.sml, line 194: Warning: match not exhaustive
        (str1 as STRstr {env={s=<pat>,t=<pat>,...},kind=k1,stamp=s1,...},str2 as STRstr {env={s=<pat>,t=<pat>,...},kind=k2,stamp=s2,table=table,...}) => ...
typing/sharing.sml, line 194: Warning: match not exhaustive
        (p' as STRstr {stamp=p,...},q' as STRstr {stamp=q,...}) => ...
typing/sharing.sml, line 194: Warning: match not exhaustive
        (nil,str) => ...
        (id :: rest,STRstr {env={s=s,...},table=table,...}) => ...

Closure: v13690

Closure: v13316 v13360 v13558 v13597 v13663 v13674 v13189
v3325 : Path [~13,0]
v3487 : Path [~15,0]
v4178 : Path [~7,0]
v4270 : Path [~5,0]
v5833 : Path [~3,0]
v6340 : Path [~11,0]
v6840 : Path [~17,0]
v9727 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v13173
v13172 : Path [~1,0]
link to closure of v13316 : Path [0,~5]

Closure: v13181
v13180 : Path [~1,0]
link to closure of v13316 : Path [0,~4]

Closure: v13177
v13180 : Path [~1,0]
v13181 : Path [0,0]

Closure: v13213
v3325 : Path [0,~2]

Closure: v13242 v13266 v13282
v3325 : Path [~18,0]
v3487 : Path [~16,0]
v6840 : Path [~17,0]
v9727 : Path [~11,0]
v13233 : Path [~12,0]
v13539 : Path [~13,0]
v13540 : Path [~14,0]
v13543 : Path [0,~1]

Closure: v13395
v13242 : Path [~19,0]
v13401 : Path [~20,0]
v13549 : Path [~3,0]
v13550 : Path [~4,0]
link to closure of v13316 : Path [0,~1]

Closure: v13369
v13400 : Path [~21,0]
v13540 : Path [~17,0]
v13549 : Path [~3,0]
v13550 : Path [~4,0]
link to closure of v13316 : Path [0,~1]

Closure: v13271
v13429 : Path [~3,0]
link to closure of v13242 : Path [0,~2]

Closure: v13278
v13430 : Path [~4,0]
link to closure of v13242 : Path [0,~2]

Closure: v13465
v13497 : Path [~10,0]
v13498 : Path [~11,0]
v13504 : Path [~16,0]
v13505 : Path [~17,0]
v13506 : Path [~18,0]
link to closure of v13242 : Path [0,~1]

Closure: v13240
v13514 : Path [~11,0]
link to closure of v13242 : Path [0,0]

Closure: v13241
v13240 : Path [~1,0]
link to closure of v13514 : Path [0,0]

Closure: v13347
v13353 : Path [~3,0]
v13354 : Path [~4,0]
link to closure of v13316 : Path [0,0]

Closure: v13325
v13353 : Path [~3,0]
v13354 : Path [~4,0]
link to closure of v13316 : Path [0,0]
[closing typing/sharing.sml]
[Compiling typing/sigmatch.sml]
signature SIGMATCH
structure SigMatch
typing/sigmatch.sml, line 371: Warning: binding not exhaustive
        str' as STRstr {sign=sign',stamp=stamp',...} = ...
typing/sigmatch.sml, line 371: Warning: binding not exhaustive
        STRstr {kind=SIGkind {stampcounts={s=<pat>,t=<pat>},...},...} = ...
typing/sigmatch.sml, line 371: Warning: binding not exhaustive
        DATACON {rep=VARIABLE access,typ=typ',...} = ...
typing/sigmatch.sml, line 371: Warning: match not exhaustive
        (STRstr {env=env,sign=sign,stamp=stamp,table=table,...},str as STRstr {env=env',...}) => ...
        (INDstr i,_) => ...
typing/sigmatch.sml, line 371: Warning: match not exhaustive
        (sgn as STRstr {kind=SIGkind <pat>,...},str) => ...

Closure: v14695

Closure: v14612 v14658 v14674
v3325 : Path [~23,0]
v3487 : Path [~21,0]
v4475 : Path [~11,0]
v5833 : Path [~3,0]
v6840 : Path [~19,0]
BOGUS : Path [0,0]

Closure: v14526 v14567
v3325 : Path [~23,0]
v3487 : Path [~21,0]
v3835 : Path [~7,0]
v4475 : Path [~11,0]
v6340 : Path [~9,0]
v6840 : Path [~19,0]
v13741 : Path [~27,0]
v14682 : Path [~24,0]
BOGUS : Path [0,0]

Closure: v14523
BOGUS : Path [0,0]

Closure: v14413 v14511 v13835 v13896
v3325 : Path [~23,0]
v3487 : Path [~21,0]
v5723 : Path [~15,0]
v5833 : Path [~3,0]
v6840 : Path [~19,0]
v9727 : Path [~17,0]
v13315 : Path [~13,0]
v14526 : Path [~28,0]
v14681 : Path [~25,0]
v14682 : Path [~24,0]
BOGUS : Path [0,0]

Closure: v13983
v3325 : Path [~23,0]
v3487 : Path [~21,0]
v5833 : Path [~3,0]
v6840 : Path [~19,0]
v9727 : Path [~17,0]
v13835 : Path [~30,2]
v14511 : Path [~30,1]
v14658 : Path [~26,1]
v14674 : Path [~26,2]
v14681 : Path [~25,0]
BOGUS : Path [0,0]

Closure: v14129 v14136 v13943 v13956 v13960 v13973 v13976
v3325 : Path [~16,0]
v3487 : Path [~15,0]
v5833 : Path [~13,0]
v6840 : Path [~14,0]
v9727 : Path [0,0]

Closure: v14060
v3325 : Path [~10,0]
v6840 : Path [~11,0]
v9727 : Path [~16,0]
v13943 : Path [~17,0]
v14110 : Path [~18,0]
v14111 : Path [0,~2]

Closure: v13900
v14372 : Path [~1,0]
link to closure of v14413 : Path [0,~3]

Closure: v14194 v13891
v3325 : Path [~22,0]
v3487 : Path [~21,0]
v5833 : Path [~20,0]
v6840 : Path [~5,0]
v9727 : Path [~15,0]
v13315 : Path [~16,0]
v13835 : Path [0,0]

Closure: v13898
v14412 : Path [~1,0]
link to closure of v14413 : Path [0,~2]

Closure: v14469 v13800 v13813
v3325 : Path [~12,0]
v3487 : Path [~11,0]
v5833 : Path [0,0]

Closure: v13808 v13811
v3325 : Path [~10,0]
v13800 : Path [~9,0]
v14428 : Path [~5,0]
v14429 : Path [~6,0]
v14433 : Path [~7,0]
v14434 : Path [~8,0]
v14435 : Path [0,~2]

Closure: v13759
v3325 : Path [~6,0]
v3835 : Path [0,~1]

Closure: v14552
v3325 : Path [~3,0]
v3487 : Path [~4,0]
v4475 : Path [~5,0]
v6340 : Path [0,0]

Closure: v13710
v13709 : Path [~1,0]
link to closure of v14612 : Path [0,~2]

Closure: v13715
v3325 : Path [~5,0]
v14665 : Path [~3,0]
v14670 : Path [~4,0]
v14671 : Path [0,~1]

Closure: v13723 v13731 v13735
v3325 : Path [~3,0]
v3487 : Path [~4,0]
v4475 : Path [0,0]
[closing typing/sigmatch.sml]
[Compiling print/printval.sig]
signature PRINTVAL
[closing print/printval.sig]
[Compiling print/printval.sml]
structure PrintVal
print/printval.sml, line 158: Warning: match not exhaustive
        (nf,l :: nil,ty :: nil) => ...
        (nf,l :: restl,ty :: restty) => ...
        (nf,nil,nil) => ...
print/printval.sml, line 158: Warning: match not exhaustive
        "nil" => ...
        "::" => ...
print/printval.sml, line 158: Warning: match not exhaustive
        CONty (_,dom :: _) => ...
        POLYty (TYFUN {body=CONty (<pat>,<pat>),...}) => ...
print/printval.sml, line 158: Warning: redundant patterns in match
        ABStyc => ...
        DEFtyc _ => ...
        DATAtyc _ => ...
        RECORDtyc nil => ...
        RECORDtyc labels => ...
  -->   _ => ...
print/printval.sml, line 158: Warning: match not exhaustive
        (obj,TYCON {kind=DATAtyc (ref <pat>),...}) => ...

Closure: v15202

Closure: v15133 v15149 v15190 v14733 v14747 v14788 v14799 v14811 v14827
v3325 : Path [~13,0]
v3487 : Path [~5,0]
v4475 : Path [~15,0]
v6000 : Path [~9,0]
v6154 : Path [~11,0]
v6840 : Path [~17,0]
v9727 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v14825
v3325 : Path [~3,0]
v4475 : Path [~6,0]
v14747 : Path [0,~8]

Closure: v14809
v3325 : Path [~3,0]
v14747 : Path [~5,0]
v14895 : Path [0,~7]

Closure: v14797
v3325 : Path [~4,0]
v4475 : Path [~5,0]
v6154 : Path [0,~6]

Closure: v14959
v3325 : Path [~20,0]
v6000 : Path [~19,0]
v6840 : Path [~15,0]
v14733 : Path [~18,0]
v14788 : Path [~3,0]
v15037 : Path [~5,0]
v15038 : Path [~10,0]
v15039 : Path [~13,0]
v15046 : Path [0,~5]

Closure: v14724
v3325 : Path [~3,0]
v3487 : Path [0,~1]
[closing print/printval.sml]
[Compiling print/printdec.sig]
signature PRINTDEC
[closing print/printdec.sig]
[Compiling print/printdec.sml]
structure PrintDec
print/printdec.sml, line 98: Warning: match not exhaustive
        TYCON {arity=arity,kind=DATAtyc dcons,name=name,...} => ...
print/printdec.sml, line 98: Warning: match not exhaustive
        TYCON {kind=ABStyc,name=name,...} => ...
print/printdec.sml, line 98: Warning: match not exhaustive
        TYCON {kind=DEFtyc (TYFUN {arity=<pat>,body=<pat>}),name=name,...} => ...
print/printdec.sml, line 98: Warning: match not exhaustive
        RVB {var=VALvar {access=LVAR <pat>,name=name,vtype=ref <pat>},...} => ...
print/printdec.sml, line 98: Warning: match not exhaustive
        VALdec vbl => ...
        VALRECdec rvbl => ...
        TYPEdec tycl => ...
        DATATYPEdec {datatycs=datatycs,withtycs=withtycs} => ...
        ABSTYPEdec {abstycs=abstycs,body=body,withtycs=withtycs} => ...
        EXCEPTIONdec ebl => ...
        STRdec strbs => ...
        FCTdec fctbs => ...
        SIGdec _ => ...
        LOCALdec (decIn,decOut) => ...
        SEQdec decl => ...
        OPENdec strvl => ...

Closure: v15511

Closure: v15282
v3325 : Path [~15,0]
v4475 : Path [~13,0]
v6340 : Path [~9,0]
v7677 : Path [~5,0]
v11292 : Path [~11,0]
v14833 : Path [~7,0]
v15502 : Path [~16,0]
BOGUS : Path [0,0]

Closure: v15227 v15240 v15244 v15249 v15251 v15258 v15261 v15263 v15265 v15268
v3325 : Path [~1,0]
v4475 : Path [0,0]

Closure: v15286
link to closure of v15227 : Path [0,~9]

Closure: v15350
link to closure of v15227 : Path [0,~5]

Closure: v15238
v3325 : Path [0,~1]
[closing print/printdec.sml]
[Compiling parse/first.sml]
structure FirstSets

Closure: v15557

Closure: v15522 v15524 v15526 v15528 v15530 v15532 v15542
v3325 : Path [~7,0]
v5192 : Path [~5,0]
v9727 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v15550 v15546
link to closure of v15522 : Path [0,~6]

Closure: v15540 v15536
link to closure of v15522 : Path [0,~5]
[closing parse/first.sml]
[Compiling parse/parse.sig]
signature PARSE
[closing parse/parse.sig]
[Compiling parse/parse.sml]
parse/parse.sml, line 230: Warning: Capitalized variable in rule: Notfound_Table
parse/parse.sml, line 1040: Warning: Capitalized variable in rule: Notfound_Table
parse/parse.sml, line 1045: Warning: Capitalized variable in rule: Notfound_Table
structure Parse
parse/parse.sml, line 1527: Warning: binding not exhaustive
        STRstr {kind=SIGkind {stampcounts={s=<pat>,t=<pat>},...},...} = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        (param as STRvar {access=LVAR <pat>,binding=pstr,name=pname},pmode) = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        sgn as STRstr {kind=SIGkind {stampcounts=<pat>,...},...} = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        (STRvar {binding=INDstr i,...},(p,_)) = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        firstId :: rest = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        ref (INDtyc x) = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        STRvar {binding=INDstr k,...} = ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        (id :: nil,STRstr {table=table,...}) => ...
        (id :: rest,STRstr {env={s=s,...},table=table,...}) => ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        VARexp (ref (v as VALvar {vtype=<pat>,...})) = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        DATATYPEdec {datatycs=datatycs,withtycs=withtycs} = ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        ((sym,const,typ) :: restdcl,rep :: restsign) => ...
        (nil,nil) => ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        TYPEdec x = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        SOME id = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        _ :: rest = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        _ :: rest = ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        TYCON {kind=DEFtyc (TYFUN {body=<pat>,...}),...} => ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        (stamp' :: stamps,tyc :: tycs) => ...
        (nil,_) => ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        (TYCON {arity=arity,home=home,kind=DATAtyc <pat>,name=name,stamp=stamp} :: rest,stamps,abstycs,dconss) => ...
        (nil,stamps,abstycs,dconss) => ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        STRvar {access=PATH ap,binding=binding,...} = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        (firstId :: rest,lastId) = ...
parse/parse.sml, line 1527: Warning: binding not exhaustive
        STRvar {access=SLOT n,binding=binding,...} = ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        (nil,str,ap) => ...
        (id :: rest,STRstr {env={s=s,...},table=table,...},ap) => ...
parse/parse.sml, line 1527: Warning: match not exhaustive
        (TYCON {name=a,...},TYCON {kind=DEFtyc (TYFUN <pat>),...}) => ...

Closure: v18313

Closure: v18285
v3325 : Path [~41,0]
BOGUS : Path [0,0]

Closure: v18275
v3325 : Path [~41,0]
v4373 : Path [~23,0]
BOGUS : Path [0,0]

Closure: v18262
v3325 : Path [~41,0]
BOGUS : Path [0,0]

Closure: v18255
v3325 : Path [~41,0]
v5192 : Path [~39,0]
v5833 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v18200 v18243
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v4105 : Path [~11,0]
v5833 : Path [~3,0]
v6154 : Path [~17,0]
v6840 : Path [~19,0]
v18254 : Path [~48,0]
BOGUS : Path [0,0]

Closure: v18197
v3325 : Path [~41,0]
v18199 : Path [~50,0]
BOGUS : Path [0,0]

Closure: v15604
v3325 : Path [~41,0]
v18199 : Path [~50,0]
BOGUS : Path [0,0]

Closure: v18182 v18186 v18190 v18193
v3325 : Path [~41,0]
v5192 : Path [~39,0]
v9727 : Path [~35,0]
v18199 : Path [~50,0]
BOGUS : Path [0,0]

Closure: v18046 v18056 v18061 v18064 v18067 v18075 v18089 v18112 v18123 v18136 v18142 v18150 v18174 v15667
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v5192 : Path [~39,0]
v9727 : Path [~35,0]
v15521 : Path [~31,0]
v18181 : Path [~53,0]
v18193 : Path [~52,3]
v18255 : Path [~47,0]
v18261 : Path [~45,0]
v18262 : Path [~44,0]
BOGUS : Path [0,0]

Closure: v17916 v17946 v17954 v17976 v18034 v15685 v15687
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v4373 : Path [~23,0]
v4753 : Path [~29,0]
v5192 : Path [~39,0]
v5723 : Path [~27,0]
v9727 : Path [~35,0]
v18174 : Path [~56,12]
v18179 : Path [~55,0]
v18255 : Path [~47,0]
v18274 : Path [~43,0]
BOGUS : Path [0,0]

Closure: v17824
v3325 : Path [~41,0]
v18285 : Path [~42,0]
BOGUS : Path [0,0]

Closure: v17739 v17787
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v5192 : Path [~39,0]
v6154 : Path [~17,0]
v9727 : Path [~35,0]
v17916 : Path [~58,0]
v17946 : Path [~58,1]
v18061 : Path [~56,2]
v18123 : Path [~56,8]
v18174 : Path [~56,12]
v18255 : Path [~47,0]
BOGUS : Path [0,0]

Closure: v17738
v9727 : Path [~35,0]
v17976 : Path [~58,3]
BOGUS : Path [0,0]

Closure: v16647 v16660 v16669 v16673 v15825 v15826 v15829 v15830 v15834 v15835 v15837 v15839 v15844 v15848 v15849 v15861 v15863 v15864 v15865 v15915 v15916 v15935 v15943 v15950 v15962 v15963 v15964 v15978 v15979 v15980 v15981 v15984 v16009 v16019 v16020 v16032 v16033 v16046 v16068 v16073 v16074 v16076 v16080 v16298 v16299 v16301 v16314 v16322 v16342
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v4373 : Path [~23,0]
v5192 : Path [~39,0]
v5723 : Path [~27,0]
v5833 : Path [~3,0]
v6154 : Path [~17,0]
v6840 : Path [~19,0]
v7909 : Path [~13,0]
v8263 : Path [~15,0]
v9727 : Path [~35,0]
v12594 : Path [~37,0]
v13315 : Path [~21,0]
v13982 : Path [~25,0]
v15521 : Path [~31,0]
v15667 : Path [~56,13]
v15685 : Path [~58,5]
v15742 : Path [~59,0]
v17732 : Path [~68,0]
v17739 : Path [~67,0]
v17787 : Path [~67,1]
v17800 : Path [~66,0]
v17804 : Path [~65,0]
v17822 : Path [~62,0]
v17823 : Path [~61,0]
v17824 : Path [~60,0]
v17916 : Path [~58,0]
v17946 : Path [~58,1]
v17954 : Path [~58,2]
v17976 : Path [~58,3]
v18045 : Path [~57,0]
v18046 : Path [~56,0]
v18061 : Path [~56,2]
v18064 : Path [~56,3]
v18067 : Path [~56,4]
v18089 : Path [~56,6]
v18112 : Path [~56,7]
v18123 : Path [~56,8]
v18136 : Path [~56,9]
v18142 : Path [~56,10]
v18150 : Path [~56,11]
v18174 : Path [~56,12]
v18179 : Path [~55,0]
v18180 : Path [~54,0]
v18181 : Path [~53,0]
v18182 : Path [~52,0]
v18186 : Path [~52,1]
v18196 : Path [~51,0]
v18243 : Path [~49,1]
v18255 : Path [~47,0]
v18258 : Path [~46,0]
v18261 : Path [~45,0]
v18262 : Path [~44,0]
v18274 : Path [~43,0]
BOGUS : Path [0,0]

Closure: v16347
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v5192 : Path [~39,0]
v16314 : Path [~69,46]
v16322 : Path [~69,47]
v16345 : Path [~70,0]
v16647 : Path [~69,0]
v18255 : Path [~47,0]
BOGUS : Path [0,0]

Closure: v16359
v3325 : Path [~41,0]
v3487 : Path [~33,0]
v5192 : Path [~39,0]
v9727 : Path [~35,0]
v12594 : Path [~37,0]
v15521 : Path [~31,0]
v15825 : Path [~69,4]
v16068 : Path [~69,38]
v16314 : Path [~69,46]
v16322 : Path [~69,47]
v16345 : Path [~70,0]
v16399 : Path [~72,0]
v16647 : Path [~69,0]
v18255 : Path [~47,0]
BOGUS : Path [0,0]

Closure: v16383 v16355
v3325 : Path [0,0]

Closure: v16380
link to closure of v16383 : Path [0,~1]

Closure: v16375
link to closure of v16383 : Path [0,~1]

Closure: v16408
link to closure of v16647 : Path [0,~48]

Closure: v16411
link to closure of v16647 : Path [0,~48]

Closure: v16445
v16457 : Path [~18,0]
v16458 : Path [~19,0]
v16461 : Path [~12,0]
v16462 : Path [~11,0]
v16464 : Path [~5,0]
v16465 : Path [~6,0]
v16468 : Path [~8,0]
v16469 : Path [~9,0]
v16470 : Path [~10,0]
v16483 : Path [~3,0]
link to closure of v16647 : Path [0,~48]

Closure: v16487
link to closure of v16647 : Path [0,~47]

Closure: v16492
link to closure of v16647 : Path [0,~47]

Closure: v16502
v5192 : Path [~1,0]
v5723 : Path [0,~46]

Closure: v16496
link to closure of v16647 : Path [0,~46]

Closure: v16501
link to closure of v16647 : Path [0,~46]

Closure: v16613
link to closure of v16647 : Path [0,~43]

Closure: v16077
v3325 : Path [0,~42]

Closure: v16069
v3325 : Path [0,~39]

Closure: v17046
link to closure of v16647 : Path [0,~38]

Closure: v16054
v17007 : Path [~3,0]
link to link to closure of v16647 : Path [0,0]

Closure: v16057
v17013 : Path [~3,0]
link to link to closure of v16647 : Path [0,0]

Closure: v16058
link to link to closure of v16647 : Path [0,0]

Closure: v17041
link to link to closure of v16647 : Path [0,0]

Closure: v17023
v3325 : Path [~4,0]
v6840 : Path [0,0]

Closure: v17040
link to link to link to closure of v16647 : Path [0,0]

Closure: v17142
v6840 : Path [0,~33]

Closure: v16111
v17212 : Path [~1,0]
link to closure of v16647 : Path [0,~32]

Closure: v17200
link to closure of v17212 : Path [0,0]

Closure: v17189
v3325 : Path [~9,0]
v3487 : Path [~4,0]
v5192 : Path [0,0]

Closure: v17188
v17189 : Path [~11,0]
v17198 : Path [~10,0]
v17201 : Path [~8,0]
v17202 : Path [~7,0]
v17204 : Path [~5,0]
link to closure of v17212 : Path [0,0]

Closure: v17187
link to closure of v17189 : Path [0,0]

Closure: v16007
v3325 : Path [~5,0]
v9727 : Path [0,0]

Closure: v17217
link to closure of v16647 : Path [0,~31]

Closure: v15982
link to link to closure of v16647 : Path [0,0]

Closure: v17222
link to closure of v16647 : Path [0,~29]

Closure: v17229
v3325 : Path [0,~27]

Closure: v15972
link to closure of v17229 : Path [0,0]

Closure: v16102
v17305 : Path [~1,0]
link to closure of v16647 : Path [0,~24]

Closure: v15954
v3325 : Path [~3,0]
v3487 : Path [0,0]

Closure: v17275
v17299 : Path [~3,0]
link to closure of v17305 : Path [0,0]

Closure: v17309
v3325 : Path [~3,0]
v9727 : Path [0,~23]

Closure: v17308
v17309 : Path [~4,0]
v17322 : Path [~3,0]
link to closure of v16647 : Path [0,~23]

Closure: v17307
link to closure of v17309 : Path [0,0]

Closure: v17319
link to closure of v17309 : Path [0,0]

Closure: v17316
link to link to closure of v17309 : Path [0,0]

Closure: v17328
v3487 : Path [~3,0]
v5192 : Path [0,~22]

Closure: v17327
v17328 : Path [~4,0]
v17344 : Path [~3,0]
link to closure of v16647 : Path [0,~22]

Closure: v17326
link to closure of v17328 : Path [0,0]

Closure: v17341
link to closure of v17328 : Path [0,0]

Closure: v17347
v3325 : Path [~3,0]
v3487 : Path [0,~21]

Closure: v17438
link to closure of v17347 : Path [0,0]

Closure: v17566 v15874 v15879 v15889 v15892 v15893 v15895 v15896 v15898 v15903 v15904
v3325 : Path [~3,0]
v3487 : Path [0,~19]

Closure: v17448
link to closure of v17566 : Path [0,~10]

Closure: v17455
link to closure of v17566 : Path [0,~9]

Closure: v17517 v17524
v3325 : Path [0,~3]

Closure: v17515 v17511
link to closure of v17566 : Path [0,~3]

Closure: v17556
link to closure of v17566 : Path [0,~2]

Closure: v15873
link to closure of v17566 : Path [0,~1]

Closure: v17582
link to closure of v16647 : Path [0,~18]

Closure: v17591
link to closure of v16647 : Path [0,~17]

Closure: v15856
v3325 : Path [0,~15]

Closure: v17605
link to closure of v16647 : Path [0,~15]

Closure: v17637
link to closure of v16647 : Path [0,~14]

Closure: v15846
v3325 : Path [0,~13]

Closure: v17649
link to closure of v16647 : Path [0,~12]

Closure: v15838
link to closure of v16647 : Path [0,~11]

Closure: v15836
link to closure of v16647 : Path [0,~10]

Closure: v17662
link to closure of v16647 : Path [0,~9]

Closure: v17669
v3325 : Path [0,~8]

Closure: v17678
link to closure of v16647 : Path [0,~7]

Closure: v17691
v17692 : Path [~3,0]
link to closure of v16647 : Path [0,~6]

Closure: v17695
link to closure of v16647 : Path [0,~5]

Closure: v17714
link to closure of v16647 : Path [0,~4]

Closure: v17727
link to closure of v16647 : Path [0,~4]

Closure: v17722
link to closure of v16647 : Path [0,~4]

Closure: v16237
v3325 : Path [0,~3]

Closure: v16674
link to closure of v16647 : Path [0,~3]

Closure: v16676
link to closure of v16647 : Path [0,~3]

Closure: v16682
v16122 : Path [~1,0]
v16237 : Path [~3,0]
link to closure of v16647 : Path [0,~3]

Closure: v16943
v3325 : Path [~4,0]
v16947 : Path [~3,0]
v16948 : Path [0,0]

Closure: v16871 v16937
v3325 : Path [~7,0]
v3487 : Path [~6,0]
v4373 : Path [0,0]

Closure: v16158
link to closure of v16237 : Path [0,0]

Closure: v16710 v16162 v16164 v16165 v16167 v16168 v16169 v16172 v16173 v16179 v16180 v16186 v16187 v16193 v16198 v16199 v16201 v16202
v3325 : Path [~10,0]
v3487 : Path [~12,0]
v5192 : Path [~11,0]
v5833 : Path [~9,0]
v6154 : Path [~8,1]
v6840 : Path [~7,0]
v9727 : Path [~6,0]
v13315 : Path [~5,0]
v15521 : Path [~4,0]
v15685 : Path [~3,0]
v15979 : Path [0,0]

Closure: v16740
link to closure of v16710 : Path [0,~17]

Closure: v16197
v16750 : Path [~3,0]
v16754 : Path [~1,0]
link to closure of v16710 : Path [0,~14]

Closure: v16769
link to closure of v16710 : Path [0,~13]

Closure: v16768
link to link to closure of v16710 : Path [0,0]

Closure: v16789
link to closure of v16710 : Path [0,~11]

Closure: v16788
link to link to closure of v16710 : Path [0,0]

Closure: v16802
link to closure of v16710 : Path [0,~9]

Closure: v16801
link to link to closure of v16710 : Path [0,0]

Closure: v16819
link to closure of v16710 : Path [0,~5]

Closure: v16163
link to closure of v16710 : Path [0,~2]

Closure: v16144
v3325 : Path [0,0]

Closure: v16666
link to closure of v16647 : Path [0,~1]

Closure: v16649
v5192 : Path [0,0]

Closure: v16648
link to closure of v16647 : Path [0,0]

Closure: v17733
link to closure of v9727 : Path [0,0]

Closure: v15790
v3325 : Path [~5,0]
v17794 : Path [~3,0]
v17796 : Path [0,~1]

Closure: v15798 v15801 v15813 v15814
v3325 : Path [~1,0]
v3487 : Path [0,0]

Closure: v17740
link to closure of v15798 : Path [0,~3]

Closure: v15803
v3325 : Path [0,~2]

Closure: v17752
link to closure of v15798 : Path [0,~2]

Closure: v17775
link to closure of v15798 : Path [0,~1]

Closure: v17778
link to closure of v15798 : Path [0,0]

Closure: v15797
link to closure of v15798 : Path [0,0]

Closure: v15760
v3325 : Path [0,0]

Closure: v17855 v15774
v3325 : Path [~6,0]
v17882 : Path [~7,0]
v17883 : Path [0,0]

Closure: v17841
v15774 : Path [~9,1]
link to closure of v17824 : Path [0,0]

Closure: v17827
v15774 : Path [~9,1]
link to closure of v17824 : Path [0,0]

Closure: v15768
v3325 : Path [~1,0]
v17870 : Path [~5,0]
v17878 : Path [0,0]

Closure: v15703
v3325 : Path [0,~3]

Closure: v17957
v5723 : Path [0,~2]

Closure: v15726
v15725 : Path [~1,0]
link to closure of v17916 : Path [0,~1]

Closure: v17938
link to closure of v17916 : Path [0,0]

Closure: v15732 v15734
v3325 : Path [~3,0]
v3487 : Path [~4,0]
v4753 : Path [~6,0]
v5192 : Path [0,0]

Closure: v18170
link to closure of v18046 : Path [0,~11]

Closure: v18165
link to closure of v18046 : Path [0,~11]

Closure: v18160 v18156
link to closure of v18046 : Path [0,~11]

Closure: v15633
v5192 : Path [~3,0]
v18129 : Path [~4,0]
v18130 : Path [~5,0]
v18131 : Path [~6,0]
v18132 : Path [0,~8]

Closure: v15642
v5192 : Path [~3,0]
v18117 : Path [~4,0]
v18118 : Path [~5,0]
v18119 : Path [~6,0]
v18120 : Path [0,~7]

Closure: v15657
v5192 : Path [~3,0]
v18107 : Path [~4,0]
v18108 : Path [~5,0]
v18109 : Path [0,~6]

Closure: v15659
link to closure of v18046 : Path [0,~6]

Closure: v15656
v18093 : Path [~9,0]
v18103 : Path [~5,0]
link to closure of v15657 : Path [0,0]

Closure: v15662
v3325 : Path [0,~5]

Closure: v18084
link to closure of v15662 : Path [0,0]

Closure: v18068
v15669 : Path [~1,0]
link to closure of v18046 : Path [0,~4]

Closure: v18205
v3325 : Path [0,0]

Closure: v15596
v3325 : Path [~6,0]
v5833 : Path [0,0]

Closure: v15568
v15567 : Path [~1,0]
link to closure of v18285 : Path [0,0]
[closing parse/parse.sml]
[Compiling basics/lambda.sml]
signature LAMBDA
structure Lambda
basics/lambda.sml, line 85: Warning: match not exhaustive
        (DATACON {rep=TAGGED i,...},e) => ...
        (DATACON {rep=TRANSPARENT,...},e) => ...
        (DATACON {rep=TRANSU,...},e) => ...
        (DATACON {rep=TRANSB,...},e) => ...
        (DATACON {rep=REF,...},e) => ...
        (DATACON {const=true,rep=VARIABLE (PATH <pat>),...},e) => ...
        (DATACON {rep=VARIABLE (PATH <pat>),...},e) => ...
        (DATACON {rep=CONSTANT i,...},e) => ...
basics/lambda.sml, line 85: Warning: match not exhaustive
        i :: nil => ...
        a :: r => ...

Closure: v18437

Closure: v18372 v18396 v18344
v3325 : Path [~11,0]
v3487 : Path [~13,0]
v5833 : Path [~5,0]
v7677 : Path [~9,0]
v18428 : Path [~15,0]
v18429 : Path [~14,0]
BOGUS : Path [0,0]
[closing basics/lambda.sml]
[Compiling codegen/opt.sml]
signature OPT
structure Opt
codegen/opt.sml, line 296: Warning: match not exhaustive
        (FN (v,a),b) => ...
codegen/opt.sml, line 296: Warning: match not exhaustive
        FN (v,e) => ...
codegen/opt.sml, line 296: Warning: match not exhaustive
        v :: nil => ...
        i :: p => ...
codegen/opt.sml, line 296: Warning: binding not exhaustive
        VAR w = ...
codegen/opt.sml, line 296: Warning: match not exhaustive
        v :: nil => ...
        i :: r => ...

Closure: v19406

Closure: v19298 v18450
v3325 : Path [~13,0]
v3487 : Path [~11,0]
v4005 : Path [~15,0]
v5723 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v19297
BOGUS : Path [0,0]

Closure: v18761 v18856 v18882 v18892 v18914 v19056 v19287 v19290 v18512 v18646 v18706
v3325 : Path [~13,0]
v3487 : Path [~11,0]
v3919 : Path [~9,0]
v4005 : Path [~15,0]
v5723 : Path [~3,0]
v8538 : Path [~7,0]
v18371 : Path [~5,0]
v18450 : Path [~16,1]
BOGUS : Path [0,0]

Closure: v18991
link to closure of v18761 : Path [0,~9]

Closure: v19238
link to closure of v18761 : Path [0,~8]

Closure: v19243
link to closure of v18761 : Path [0,~8]

Closure: v19220 v18544 v18546 v18555
v3325 : Path [~9,0]
v4005 : Path [~8,0]
v18512 : Path [~6,0]
v19226 : Path [~5,0]
v19227 : Path [~4,0]
v19229 : Path [0,~5]

Closure: v19080
link to closure of v19220 : Path [0,~3]

Closure: v19153
link to closure of v19220 : Path [0,~3]

Closure: v18654
v3325 : Path [~7,0]
v18450 : Path [~6,0]
v18984 : Path [~5,0]
v18985 : Path [~4,0]
v18986 : Path [0,~4]

Closure: v18929
link to closure of v18654 : Path [0,0]

Closure: v18683
link to closure of v18761 : Path [0,~3]

Closure: v18895
link to closure of v18761 : Path [0,~3]

Closure: v18899
link to closure of v18761 : Path [0,~3]

Closure: v18883
v18888 : Path [~3,0]
link to closure of v18761 : Path [0,~2]

Closure: v18711
v18708 : Path [~1,0]
link to closure of v18761 : Path [0,~1]

Closure: v18718
v3325 : Path [~4,0]
v18450 : Path [0,0]

Closure: v18771
link to closure of v18718 : Path [0,0]

Closure: v18775
link to closure of v18718 : Path [0,0]

Closure: v18766
link to closure of v18718 : Path [0,0]

Closure: v18791
v18450 : Path [0,0]

Closure: v18783
v18791 : Path [~7,0]
link to closure of v18718 : Path [0,0]

Closure: v18806
link to closure of v18718 : Path [0,0]

Closure: v19342 v19347 v19379 v18477
v3325 : Path [~1,0]
v4005 : Path [~4,0]
v5723 : Path [~3,0]
v18452 : Path [0,0]

Closure: v19303
link to closure of v19342 : Path [0,~3]

Closure: v19299
link to closure of v19342 : Path [0,~3]

Closure: v18468
v3325 : Path [0,~1]
[closing codegen/opt.sml]
[Compiling translate/mcprint.sml]
signature MCprint
structure MCprint
translate/mcprint.sml, line 172: Warning: match not exhaustive
        (c,l) :: nil => ...
        (c,l) :: more => ...
translate/mcprint.sml, line 172: Warning: match not exhaustive
        (v :: nil,l :: nil) => ...
        (v :: vs,l :: ls) => ...
        (nil,nil) => ...

Closure: v19898

Closure: v19886
v3325 : Path [~15,0]
v19889 : Path [~16,0]
BOGUS : Path [0,0]

Closure: v19548 v19870 v19878 v19881 v19435 v19513 v19518
v3325 : Path [~15,0]
v4475 : Path [~13,0]
v5723 : Path [~3,0]
v7677 : Path [~9,0]
v11292 : Path [~11,0]
v19423 : Path [~18,0]
v19886 : Path [~17,0]
v19889 : Path [~16,0]
BOGUS : Path [0,0]

Closure: v19459
link to closure of v19548 : Path [0,~5]

Closure: v19467
link to closure of v19548 : Path [0,~5]

Closure: v19626
v3325 : Path [0,~5]

Closure: v19491
v3325 : Path [0,~5]

Closure: v19508
v3325 : Path [0,~5]

Closure: v19449
v19435 : Path [0,~4]

Closure: v19546
v19545 : Path [~1,0]
link to closure of v19548 : Path [0,0]

Closure: v19522
v3325 : Path [~1,0]
v5723 : Path [0,0]

Closure: v19531
link to closure of v19522 : Path [0,0]

Closure: v19560
link to closure of v19522 : Path [0,0]
[closing translate/mcprint.sml]
[Compiling translate/mcopt.sml]
signature MCopt
structure MCopt
translate/mcopt.sml, line 233: Warning: match not exhaustive
        APPpat (DATACON {name=r2,...},_) => ...
        CONpat _ => ...
translate/mcopt.sml, line 233: Warning: match not exhaustive
        CONpat (DATACON {name=r2,...}) => ...
        APPpat _ => ...
translate/mcopt.sml, line 233: Warning: match not exhaustive
        INTpat j => ...
translate/mcopt.sml, line 233: Warning: match not exhaustive
        REALpat s => ...
translate/mcopt.sml, line 233: Warning: match not exhaustive
        STRINGpat t => ...

Closure: v20650

Closure: v20454 v20490 v20579 v19911 v19916 v19921 v19967 v19972
v3325 : Path [~15,0]
v3487 : Path [~13,0]
v4475 : Path [~11,0]
BOGUS : Path [0,0]

Closure: v20083 v19990 v20001 v20016 v20031 v20039 v20047 v20055 v20060
v3325 : Path [~15,0]
v3487 : Path [~13,0]
v19911 : Path [~19,3]
v19916 : Path [~19,4]
v19921 : Path [~19,5]
v19986 : Path [~20,0]
v20454 : Path [~19,0]
v20490 : Path [~19,1]
BOGUS : Path [0,0]

Closure: v20041
v20256 : Path [~1,0]
link to closure of v20083 : Path [0,~5]

Closure: v20535
v3325 : Path [~5,0]
v20553 : Path [0,~6]

Closure: v20531
v3325 : Path [~5,0]
v20555 : Path [0,~6]

Closure: v20527
v3325 : Path [~5,0]
v20557 : Path [0,~6]

Closure: v20515
v3325 : Path [~6,0]
v4475 : Path [0,~6]

Closure: v20501
v3325 : Path [~7,0]
v4475 : Path [0,~6]

Closure: v19937
v19936 : Path [~1,0]
link to closure of v20454 : Path [0,~2]

Closure: v19933
v3325 : Path [0,0]

Closure: v19982
v3325 : Path [0,0]
[closing translate/mcopt.sml]
[Compiling translate/mc.sml]
signature MC
structure MC
translate/mc.sml, line 493: Warning: binding not exhaustive
        ((con,lexp) :: nil,_) = ...
translate/mc.sml, line 493: Warning: binding not exhaustive
        ((DATAcon dcon,list) :: nil,_) = ...
translate/mc.sml, line 493: Warning: match not exhaustive
        INTpat j => ...
translate/mc.sml, line 493: Warning: match not exhaustive
        REALpat s => ...
translate/mc.sml, line 493: Warning: match not exhaustive
        STRINGpat t => ...

Closure: v22362

Closure: v22222 v22257 v22264 v22267 v22277 v22288 v22292 v22303 v22307 v22328 v20722
v3325 : Path [~15,0]
v3487 : Path [~13,0]
v18760 : Path [~7,0]
v22349 : Path [~22,0]
v22350 : Path [~21,0]
BOGUS : Path [0,0]

Closure: v22217
BOGUS : Path [0,0]

Closure: v20744
BOGUS : Path [0,0]

Closure: v21063 v21094 v21124 v21152 v21941 v22030 v20919 v20972 v21015 v21028
v3325 : Path [~15,0]
v3487 : Path [~13,0]
v4475 : Path [~17,0]
v11292 : Path [~11,0]
v18371 : Path [~5,0]
v19547 : Path [~19,0]
v20082 : Path [~9,0]
v20722 : Path [~23,10]
v22203 : Path [~25,0]
v22216 : Path [~24,0]
v22222 : Path [~23,0]
v22257 : Path [~23,1]
v22264 : Path [~23,2]
v22267 : Path [~23,3]
v22277 : Path [~23,4]
v22288 : Path [~23,5]
v22292 : Path [~23,6]
v22303 : Path [~23,7]
v22351 : Path [~20,0]
BOGUS : Path [0,0]

Closure: v21030
v21191 : Path [~1,0]
link to closure of v21063 : Path [0,~9]

Closure: v21031
v21030 : Path [~1,0]
link to closure of v21191 : Path [0,0]

Closure: v21275
link to closure of v21063 : Path [0,~8]

Closure: v21273
link to closure of v21063 : Path [0,~8]

Closure: v21009
v3325 : Path [~13,0]
v3487 : Path [~8,0]
v20722 : Path [0,~8]

Closure: v20970
v3487 : Path [~1,0]
v4475 : Path [0,~7]

Closure: v20937
v3487 : Path [~9,0]
v4475 : Path [0,0]

Closure: v20958
v3487 : Path [~11,0]
v4475 : Path [0,0]

Closure: v21481
v3487 : Path [0,~6]

Closure: v21669
v3487 : Path [~12,0]
v18371 : Path [~13,0]
v20082 : Path [0,~6]

Closure: v21556
v21699 : Path [~13,0]
link to closure of v21063 : Path [0,~6]

Closure: v21579
v21699 : Path [~13,0]
link to closure of v21063 : Path [0,~6]

Closure: v21555
link to closure of v21063 : Path [0,~6]

Closure: v21553
link to closure of v21063 : Path [0,~6]

Closure: v20913
v3325 : Path [~19,0]
v3487 : Path [~12,0]
v20722 : Path [0,~6]

Closure: v21663
v21699 : Path [~13,0]
link to closure of v21063 : Path [0,~6]

Closure: v21716
v3487 : Path [~12,0]
v18371 : Path [~13,0]
v20082 : Path [0,~6]

Closure: v21734
v21705 : Path [~13,0]
link to closure of v21063 : Path [0,~6]

Closure: v21746
v21705 : Path [~13,0]
link to closure of v21063 : Path [0,~6]

Closure: v21902
link to closure of v21063 : Path [0,~6]

Closure: v21901
link to closure of v21063 : Path [0,~6]

Closure: v21853
v3325 : Path [~12,0]
v3487 : Path [~19,0]
v20722 : Path [0,~6]

Closure: v21909
v21705 : Path [~13,0]
link to closure of v21063 : Path [0,~6]

Closure: v20820
v3325 : Path [~1,0]
v3487 : Path [0,~5]

Closure: v20814
v22193 : Path [~6,0]
v22194 : Path [~7,0]
v22197 : Path [~9,0]
link to closure of v20820 : Path [0,0]

Closure: v20760
v3487 : Path [~13,0]
v22044 : Path [~10,0]
v22150 : Path [~6,0]
v22193 : Path [~7,0]
v22194 : Path [~9,0]
v22197 : Path [0,0]

Closure: v20769
v3325 : Path [~13,0]
v3487 : Path [~10,0]
v22059 : Path [~6,0]
v22151 : Path [~7,0]
v22193 : Path [~9,0]
v22194 : Path [0,0]

Closure: v20778
v3325 : Path [~13,0]
v3487 : Path [~10,0]
v22074 : Path [~6,0]
v22152 : Path [~7,0]
v22193 : Path [~9,0]
v22194 : Path [0,0]

Closure: v20788
v3487 : Path [~15,0]
v4475 : Path [~10,0]
v22095 : Path [~11,0]
v22153 : Path [~6,0]
v22157 : Path [~7,0]
v22193 : Path [~9,0]
v22194 : Path [0,0]

Closure: v20804
v3325 : Path [~16,0]
v3487 : Path [~11,0]
v4475 : Path [~12,0]
v22123 : Path [~13,0]
v22163 : Path [~6,0]
v22164 : Path [~7,0]
v22167 : Path [~9,0]
v22193 : Path [0,0]

Closure: v22098
link to closure of v20804 : Path [0,0]

Closure: v21989 v20860
v3325 : Path [~1,0]
v3487 : Path [0,~4]

Closure: v21946
v21961 : Path [~8,0]
link to closure of v21989 : Path [0,~1]

Closure: v21952
v21962 : Path [~8,0]
link to closure of v21989 : Path [0,~1]

Closure: v21958
v21963 : Path [~8,0]
link to closure of v21989 : Path [0,~1]

Closure: v20835
v3325 : Path [~1,0]
v3487 : Path [0,0]

Closure: v21039
v3325 : Path [0,~2]

Closure: v21048
v21117 : Path [~7,0]
link to closure of v21063 : Path [0,~1]

Closure: v21057
v21087 : Path [~7,0]
link to closure of v21063 : Path [0,0]

Closure: v21059
v21087 : Path [~7,0]
link to closure of v21063 : Path [0,0]

Closure: v20746
v22215 : Path [~1,0]
link to closure of v20744 : Path [0,0]

Closure: v20672
v20671 : Path [~1,0]
link to closure of v22222 : Path [0,~9]

Closure: v20667
link to closure of v20671 : Path [0,0]

Closure: v20669
v22341 : Path [~1,0]
link to closure of v20667 : Path [0,0]

Closure: v20683
v3487 : Path [0,~8]

Closure: v20685
v22325 : Path [~1,0]
link to closure of v20683 : Path [0,0]

Closure: v20686
v20685 : Path [~1,0]
link to closure of v22325 : Path [0,0]

Closure: v20693
v22300 : Path [~4,0]
link to closure of v22222 : Path [0,~6]

Closure: v20694
v22300 : Path [~4,0]
link to closure of v22222 : Path [0,~6]

Closure: v20702
v22285 : Path [~4,0]
link to closure of v22222 : Path [0,~4]

Closure: v20703
v22285 : Path [~4,0]
link to closure of v22222 : Path [0,~4]

Closure: v20731
v22233 : Path [~3,0]
v22235 : Path [~5,0]
link to closure of v22222 : Path [0,0]
[closing translate/mc.sml]
[Compiling translate/nonrec.sml]
structure Nonrec

Closure: v22515

Closure: v22405
v3325 : Path [~3,0]
v22368 : Path [~4,0]
BOGUS : Path [0,0]

Closure: v22374 v22393
v3325 : Path [~12,0]
v22368 : Path [0,0]

Closure: v22413
link to closure of v22374 : Path [0,~1]

Closure: v22419
link to closure of v22374 : Path [0,~1]

Closure: v22435
link to closure of v22374 : Path [0,0]

Closure: v22444
link to closure of v22374 : Path [0,0]

Closure: v22449
link to closure of v22374 : Path [0,0]
[closing translate/nonrec.sml]
[Compiling translate/equal.sml]
signature EQUAL
structure Equal
translate/equal.sml, line 127: Warning: binding not exhaustive
        VALvar {access=PATH p,...} = ...

Closure: v23044

Closure: v22971 v22987 v22522
v3325 : Path [~19,0]
v3487 : Path [~17,0]
v4753 : Path [~9,0]
v5833 : Path [~3,0]
v6840 : Path [~21,0]
v9727 : Path [~11,0]
BOGUS : Path [0,0]

Closure: v22598
v3325 : Path [~19,0]
v3487 : Path [~17,0]
v4753 : Path [~9,0]
v5723 : Path [~13,0]
v6154 : Path [~15,0]
v6340 : Path [~7,0]
v6840 : Path [~21,0]
v9727 : Path [~11,0]
v18371 : Path [~5,0]
v22522 : Path [~22,2]
v22535 : Path [~23,0]
v22969 : Path [~25,0]
v22970 : Path [~24,0]
v22971 : Path [~22,0]
v22987 : Path [~22,1]
BOGUS : Path [0,0]

Closure: v22935 v22948 v22590
v3325 : Path [~6,0]
v3487 : Path [~5,0]
v5723 : Path [0,0]

Closure: v22605
link to closure of v22598 : Path [0,0]

Closure: v22612
link to closure of v22598 : Path [0,0]

Closure: v22650
v18371 : Path [~21,0]
v22590 : Path [~20,0]
v22665 : Path [~5,0]
v22666 : Path [0,~2]

Closure: v22621
v22650 : Path [~25,0]
v22665 : Path [~21,0]
v22969 : Path [0,~2]

Closure: v22643
v22650 : Path [~25,0]
v22665 : Path [~21,0]
v22969 : Path [0,~2]

Closure: v22588
v6154 : Path [~21,0]
v22590 : Path [~20,0]
v22665 : Path [0,~2]

Closure: v22717
v18371 : Path [~5,0]
v22590 : Path [~20,0]
v22680 : Path [~21,0]
v22707 : Path [0,~2]

Closure: v22732
v22709 : Path [~21,0]
v22717 : Path [~25,0]
v22969 : Path [0,~2]

Closure: v22739
v22709 : Path [~21,0]
v22717 : Path [~25,0]
v22969 : Path [0,~2]

Closure: v22746
v6154 : Path [~20,0]
v22590 : Path [~21,0]
v22707 : Path [0,~2]

Closure: v22793
v18371 : Path [~5,0]
v22590 : Path [~15,0]
v22680 : Path [~16,0]
v22783 : Path [0,~2]

Closure: v22808
v22785 : Path [~16,0]
v22793 : Path [~20,0]
v22969 : Path [0,~2]

Closure: v22815
v22785 : Path [~16,0]
v22793 : Path [~20,0]
v22969 : Path [0,~2]

Closure: v22822
v6154 : Path [~15,0]
v22590 : Path [~16,0]
v22783 : Path [0,~2]

Closure: v22872
v18371 : Path [~5,0]
v22590 : Path [~13,0]
v22680 : Path [~14,0]
v22862 : Path [0,~2]

Closure: v22887
v22864 : Path [~14,0]
v22872 : Path [~18,0]
v22969 : Path [0,~2]

Closure: v22894
v22864 : Path [~14,0]
v22872 : Path [~18,0]
v22969 : Path [0,~2]

Closure: v22901
v6154 : Path [~13,0]
v22590 : Path [~14,0]
v22862 : Path [0,~2]

Closure: v22552
v6840 : Path [~1,0]
v22535 : Path [0,0]
[closing translate/equal.sml]
[Compiling translate/unboxed.sml]
structure Unboxed

Closure: v23182

Closure: v23069 v23108 v23058
v3325 : Path [~5,0]
v3487 : Path [~7,0]
v6154 : Path [~11,0]
v8538 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v23144
link to closure of v23069 : Path [0,~2]
[closing translate/unboxed.sml]
[Compiling translate/translate.sml]
signature TRANSLATE
structure Translate

Closure: v23968

Closure: v23903 v23918 v23922
v3487 : Path [~31,0]
v6154 : Path [~23,0]
v18371 : Path [~7,0]
v23951 : Path [~32,0]
BOGUS : Path [0,0]

Closure: v23881 v23888 v23893
v9727 : Path [~13,0]
v18371 : Path [~7,0]
v23898 : Path [~38,0]
v23899 : Path [~37,0]
v23900 : Path [~36,0]
v23951 : Path [~32,0]
BOGUS : Path [0,0]

Closure: v23217 v23246 v23252 v23262 v23271 v23322 v23325 v23329 v23380
v3325 : Path [~29,0]
v3487 : Path [~31,0]
v6154 : Path [~23,0]
v8538 : Path [~17,0]
v11292 : Path [~15,0]
v18371 : Path [~7,0]
v21062 : Path [~27,0]
v22404 : Path [~25,0]
v22597 : Path [~21,0]
v23068 : Path [~19,0]
v23880 : Path [~40,0]
v23881 : Path [~39,0]
v23888 : Path [~39,1]
v23893 : Path [~39,2]
v23901 : Path [~35,0]
v23902 : Path [~34,0]
v23918 : Path [~33,1]
v23922 : Path [~33,2]
v23951 : Path [~32,0]
BOGUS : Path [0,0]

Closure: v23409
link to closure of v23217 : Path [0,~8]

Closure: v23398
v23380 : Path [0,~8]

Closure: v23392
link to closure of v23217 : Path [0,~8]

Closure: v23388
link to closure of v23217 : Path [0,~8]

Closure: v23348
v3487 : Path [0,~8]

Closure: v23441
link to closure of v23217 : Path [0,~8]

Closure: v23429
link to closure of v23217 : Path [0,~8]

Closure: v23447
link to closure of v23217 : Path [0,~8]

Closure: v23280
v23710 : Path [~3,0]
link to closure of v23217 : Path [0,~5]

Closure: v23619
link to closure of v23217 : Path [0,~5]

Closure: v23299
v3325 : Path [0,~5]

Closure: v23301
link to closure of v23217 : Path [0,~5]

Closure: v23303
link to closure of v23217 : Path [0,~5]

Closure: v23654
link to closure of v23217 : Path [0,~5]

Closure: v23669
link to closure of v23217 : Path [0,~5]

Closure: v23684
link to closure of v23217 : Path [0,~5]

Closure: v23320
link to closure of v23217 : Path [0,~5]

Closure: v23321
link to closure of v23217 : Path [0,~5]

Closure: v23545
link to closure of v23217 : Path [0,~5]

Closure: v23298
link to closure of v23299 : Path [0,0]

Closure: v23595
link to closure of v23710 : Path [0,0]

Closure: v23790
link to closure of v23217 : Path [0,~1]

Closure: v23843
link to closure of v23217 : Path [0,~1]

Closure: v23234 v23244
v3325 : Path [~7,0]
v3487 : Path [~1,0]
v11292 : Path [0,~1]
[closing translate/translate.sml]
[Compiling codegen/cgoptions.sml]
structure CGoptions

Closure: v23976
[closing codegen/cgoptions.sml]
[Compiling codegen/codenv.sml]
signature CODENV
functor Codenv
codegen/codenv.sml, line 191: Warning: match not exhaustive
        (freevars,(e as FN (<pat>,<pat>),env,_)) => ...
        (freevars,(FIX (vl as <pat>,el,b),env,offset)) => ...
codegen/codenv.sml, line 191: Warning: match not exhaustive
        (freevars,(e as FN (<pat>,<pat>),env,_)) => ...
        (freevars,(FIX (vl as <pat>,el,b),env,offset)) => ...
codegen/codenv.sml, line 191: Warning: match not exhaustive
        (nil,free,close) => ...
        (v :: vl,free,_ :: close) => ...
codegen/codenv.sml, line 191: Warning: match not exhaustive
        (nil,free,close) => ...
        (v :: vl,free,_ :: close) => ...
codegen/codenv.sml, line 191: Warning: match not exhaustive
        (nil,nil) => ...
        (v :: vl,acc :: accl) => ...

Closure: v24641

Closure: v23981
v3325 : Path [~13,0]
v4005 : Path [~9,0]
v4475 : Path [~7,0]
v5723 : Path [~5,0]
v18371 : Path [~3,0]
v18760 : Path [~15,0]
v23973 : Path [~11,0]
BOGUS : Path [0,0]

Closure: v24615 v23989
v23986 : Path [~4,0]
link to closure of v3325 : Path [0,0]

Closure: v24452 v24511 v24551 v24564 v24571 v24577 v24005
v3325 : Path [~6,0]
v4475 : Path [~3,0]
v23973 : Path [0,0]

Closure: v24204 v24208 v24348 v24087
v3325 : Path [~1,0]
v4005 : Path [~4,0]
v18760 : Path [~5,1]
v23973 : Path [~6,0]
v23981 : Path [~8,0]
v23986 : Path [~7,0]
v23989 : Path [~7,1]
v23998 : Path [~7,3]
v24076 : Path [~7,5]
v24452 : Path [~5,0]
v24511 : Path [0,0]

Closure: v24203
link to closure of v3325 : Path [0,0]

Closure: v24085
v23998 : Path [~4,0]
v24076 : Path [0,~3]

Closure: v24135
v24134 : Path [~1,0]
link to closure of v24204 : Path [0,~2]

Closure: v24115 v24121
v24405 : Path [~11,0]
link to closure of v24134 : Path [0,0]

Closure: v24127
v23981 : Path [~13,0]
v24386 : Path [0,0]

Closure: v24369
link to closure of v24134 : Path [0,0]

Closure: v24370
link to closure of v24134 : Path [0,0]

Closure: v24132
v24410 : Path [~4,0]
link to closure of v24134 : Path [0,0]

Closure: v24097
v24410 : Path [~4,0]
link to closure of v24134 : Path [0,0]

Closure: v24101
link to closure of v24134 : Path [0,0]

Closure: v24198
v24197 : Path [~1,0]
link to closure of v24204 : Path [0,~1]

Closure: v24171
v24313 : Path [~13,0]
link to closure of v24197 : Path [0,0]

Closure: v24177 v24183
v24305 : Path [~13,0]
v24314 : Path [~12,0]
link to closure of v24197 : Path [0,0]

Closure: v24189
v23981 : Path [~15,0]
v24281 : Path [0,0]

Closure: v24259
link to closure of v24197 : Path [0,0]

Closure: v24260
link to closure of v24197 : Path [0,0]

Closure: v24194
v24330 : Path [~4,0]
link to closure of v24197 : Path [0,0]

Closure: v24147
v24240 : Path [~12,0]
link to closure of v24197 : Path [0,0]

Closure: v24149
v24330 : Path [~4,0]
link to closure of v24197 : Path [0,0]

Closure: v24156
v24241 : Path [~11,0]
link to closure of v24197 : Path [0,0]

Closure: v24026
link to closure of v24452 : Path [0,~2]

Closure: v24036 v24044
v3325 : Path [0,~1]

Closure: v24057 v24064 v24072
v3325 : Path [~8,0]
v4475 : Path [0,0]

Closure: v23994
v23991 : Path [~1,0]
link to closure of v24615 : Path [0,0]
[closing codegen/codenv.sml]
[Compiling codegen/machine.sig]
signature MACHINE
signature MACHINECODE
signature ASSEMBLYCODE
[closing codegen/machine.sig]
[Compiling codegen/switcher.sml]
signature SWITCHER
functor Switcher

Closure: v25135

Closure: v24691
v3325 : Path [~11,0]
v3487 : Path [~9,0]
v4475 : Path [~7,0]
v7677 : Path [~5,0]
v18371 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v25095 v25101 v25111 v24697
v3487 : Path [0,0]

Closure: v25078
link to closure of v3325 : Path [0,0]

Closure: v24781 v25054 v25068
v3325 : Path [~1,0]
v3487 : Path [~4,3]
v24691 : Path [~4,0]
v24697 : Path [~4,1]
v25095 : Path [~4,2]
v25101 : Path [~3,0]
v25111 : Path [0,0]

Closure: v24994 v25009
v3325 : Path [~10,0]
v24691 : Path [~3,0]
v24697 : Path [~4,0]
v25043 : Path [~5,0]
v25045 : Path [0,0]

Closure: v24702
v24699 : Path [~1,0]
link to closure of v25095 : Path [0,~2]

Closure: v24709
v24706 : Path [~1,0]
link to closure of v25095 : Path [0,~1]
[closing codegen/switcher.sml]
[Compiling codegen/codegen.sml]
signature CODEGEN
functor Codegen
codegen/codegen.sml, line 260: Warning: binding not exhaustive
        frag :: rest = ...
codegen/codegen.sml, line 260: Warning: binding not exhaustive
        (_,(frag as (_,_,env)) :: nil,close) = ...

Closure: v25947

Closure: v25139
v3325 : Path [~17,0]
v3487 : Path [~13,0]
v3577 : Path [~11,0]
v18760 : Path [~19,0]
v23973 : Path [~15,0]
v24202 : Path [~9,0]
v24780 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v25927 v25930
v3325 : Path [~5,0]
v25146 : Path [~7,0]
v25935 : Path [~6,0]
v25936 : Path [0,0]

Closure: v25900 v25906 v25912
v3325 : Path [~1,0]
v23973 : Path [~13,0]
v25139 : Path [~12,0]
v25918 : Path [~11,0]
v25920 : Path [~10,0]
v25921 : Path [~9,0]
v25923 : Path [0,0]

Closure: v25321 v25894 v25180
v3325 : Path [~1,0]
v3487 : Path [~3,0]
v18760 : Path [~4,0]
v23973 : Path [~9,0]
v25139 : Path [~12,0]
v25142 : Path [~11,0]
v25144 : Path [~10,0]
v25173 : Path [~8,1]
v25897 : Path [0,0]

Closure: v25333
v3325 : Path [~5,0]
v3487 : Path [0,0]

Closure: v25317
v3325 : Path [~6,0]
v25333 : Path [0,0]

Closure: v25307
v3325 : Path [0,0]

Closure: v25305
v3325 : Path [~1,0]
v18760 : Path [0,0]

Closure: v25831 v25202
v3325 : Path [0,0]

Closure: v25227
link to closure of v25305 : Path [0,0]

Closure: v25231
v25350 : Path [~14,0]
v25352 : Path [~13,0]
link to closure of v25305 : Path [0,0]

Closure: v25489
v25139 : Path [~34,0]
v25305 : Path [~33,0]
v25502 : Path [~24,0]
v25503 : Path [~26,0]
v25616 : Path [~4,0]
v25619 : Path [0,0]

Closure: v25446
v25861 : Path [0,0]

Closure: v25460
v25861 : Path [0,0]

Closure: v25470
v25861 : Path [0,0]

Closure: v25480
v25861 : Path [0,0]

Closure: v25504
v25861 : Path [0,0]

Closure: v25641
v25861 : Path [0,0]

Closure: v25652
v25861 : Path [0,0]

Closure: v25663
v25861 : Path [0,0]

Closure: v25674
v25861 : Path [0,0]

Closure: v25685
v25861 : Path [0,0]

Closure: v25696
v25861 : Path [0,0]

Closure: v25707
v25861 : Path [0,0]

Closure: v25718
v25861 : Path [0,0]

Closure: v25729
v25861 : Path [0,0]

Closure: v25740
v25861 : Path [0,0]

Closure: v25751
v25861 : Path [0,0]

Closure: v25762
v25861 : Path [0,0]

Closure: v25773
v25861 : Path [0,0]

Closure: v25784
v25861 : Path [0,0]

Closure: v25795
v25861 : Path [0,0]

Closure: v25290
v25139 : Path [0,0]

Closure: v25295
v3325 : Path [~9,0]
v25527 : Path [0,0]
[closing codegen/codegen.sml]
[Compiling codegen/reopen.sml]
signature SYS
functor Reopen
codegen/reopen.sml, line 157: Warning: binding not exhaustive
        CLOSUREval x = ...
codegen/reopen.sml, line 157: Warning: match not exhaustive
        f' as FN (v,b) => ...
        f' as VAR w => ...

Closure: v26348

Closure: v25951
v3325 : Path [~13,0]
v3487 : Path [~5,0]
v4005 : Path [~9,0]
v5723 : Path [~3,0]
v18760 : Path [~11,0]
v19547 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v26326
v3325 : Path [~1,0]
v25951 : Path [0,0]

Closure: v26084 v26254 v26272 v26277 v26293 v26307
v3325 : Path [~1,0]
v3487 : Path [~3,0]
v4005 : Path [~6,0]
v5723 : Path [~5,0]
v18760 : Path [~4,0]
v19547 : Path [0,0]

Closure: v26309
v25966 : Path [~1,0]
link to closure of v26084 : Path [0,~5]

Closure: v26278
v25974 : Path [~1,0]
link to closure of v26084 : Path [0,~3]

Closure: v26273
v25978 : Path [~1,0]
link to closure of v26084 : Path [0,~2]

Closure: v25989
v3487 : Path [~3,0]
v26267 : Path [~5,0]
v26269 : Path [0,~1]

Closure: v26203 v26211 v26236 v26241 v26074
v3325 : Path [~5,0]
v3487 : Path [~4,0]
v4005 : Path [0,0]

Closure: v26087
link to closure of v26084 : Path [0,0]

Closure: v26072
v3325 : Path [~1,0]
v18760 : Path [0,~4]

Closure: v26028
v26103 : Path [~8,0]
v26159 : Path [~5,0]
link to closure of v26072 : Path [0,0]

Closure: v26121
link to closure of v26072 : Path [0,0]

Closure: v26136
link to closure of v26072 : Path [0,0]

Closure: v26145
link to closure of v26072 : Path [0,0]

Closure: v26092
link to closure of v26103 : Path [0,0]

Closure: v26212
v3487 : Path [~7,0]
v25951 : Path [~3,0]
v25953 : Path [0,~1]

Closure: v26015
v26207 : Path [~3,0]
v26208 : Path [~4,0]
link to closure of v26203 : Path [0,0]

Closure: v26328
v3325 : Path [~7,0]
v26332 : Path [~6,0]
v26333 : Path [0,0]
[closing codegen/reopen.sml]
[Compiling codegen/backpatch.sml]
signature BACKPATCH
functor Backpatch

Closure: v26636

Closure: v26359
v3325 : Path [~7,0]
v3487 : Path [~5,0]
v3577 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v26561 v26625
v3325 : Path [0,0]

Closure: v26555
v3325 : Path [~3,0]
v26365 : Path [~6,0]
v26559 : Path [~5,0]
v26560 : Path [0,0]

Closure: v26478 v26535 v26538 v26544 v26547 v26550
v3325 : Path [~3,0]
v3487 : Path [~8,0]
v26365 : Path [~6,0]
v26554 : Path [~5,0]
v26559 : Path [~4,0]
v26560 : Path [~4,1]
v26561 : Path [0,0]

Closure: v26445
v26525 : Path [~9,0]
v26526 : Path [~8,0]
v26531 : Path [~4,0]
v26532 : Path [~5,0]
link to closure of v26478 : Path [0,0]

Closure: v26448 v26473
v3325 : Path [~1,0]
v26365 : Path [0,0]

Closure: v26418
v26417 : Path [~1,0]
link to closure of v26561 : Path [0,0]

Closure: v26391 v26413
v3325 : Path [~3,0]
v26417 : Path [0,0]

Closure: v26415
v3325 : Path [~4,0]
v26391 : Path [~4,1]
v26413 : Path [~1,0]
v26418 : Path [~3,0]
v26616 : Path [0,0]
[closing codegen/backpatch.sml]
[Compiling bignums/bitops.sml]
structure BitOps

Closure: v26697

Closure: v26638 v26642 v26645 v26652 v26659
v3325 : Path [~3,0]
BOGUS : Path [0,0]
[closing bignums/bitops.sml]
[Compiling bignums/bigint.sig]
signature BIGINT
[closing bignums/bigint.sig]
[Compiling bignums/bigint.sml]
structure Bigint

Closure: v27201

Closure: v27088 v27098 v27103 v27127 v27151 v27178 v27185 v27188
v3325 : Path [~5,0]
v26661 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v27074
v3325 : Path [~5,0]
v26774 : Path [~7,0]
v27088 : Path [~6,0]
v27127 : Path [~6,3]
v27185 : Path [~6,6]
BOGUS : Path [0,0]

Closure: v26938 v26969 v27014 v27066
v3325 : Path [~5,0]
v26661 : Path [~3,0]
v26785 : Path [~9,0]
v27088 : Path [~6,0]
v27127 : Path [~6,3]
v27151 : Path [~6,4]
v27185 : Path [~6,6]
BOGUS : Path [0,0]

Closure: v26912 v26925
v3325 : Path [~5,0]
v26661 : Path [~3,0]
v26936 : Path [~12,0]
v26937 : Path [~11,0]
v26938 : Path [~10,0]
v27088 : Path [~6,0]
v27185 : Path [~6,6]
BOGUS : Path [0,0]

Closure: v26897 v26907
v26911 : Path [~14,0]
v26912 : Path [~13,0]
v27014 : Path [~10,2]
v27127 : Path [~6,3]
BOGUS : Path [0,0]

Closure: v26877 v26880
v3325 : Path [~1,0]
v26661 : Path [0,0]

Closure: v26804
v3325 : Path [~13,0]
v27049 : Path [~12,0]
v27050 : Path [~8,0]
v27055 : Path [~6,0]
v27057 : Path [~7,0]
v27058 : Path [0,~2]

Closure: v27023
v3325 : Path [~13,0]
v27049 : Path [0,~2]

Closure: v26811
v3325 : Path [~4,0]
v27031 : Path [0,0]

Closure: v26842
v3325 : Path [~12,0]
v26999 : Path [~10,0]
v27001 : Path [~9,0]
v27002 : Path [~8,0]
v27003 : Path [~6,0]
v27006 : Path [0,~1]

Closure: v26975
link to closure of v26938 : Path [0,~1]

Closure: v26833 v26840
v3325 : Path [~3,0]
v26995 : Path [~1,0]
v26998 : Path [0,0]

Closure: v26859
v3325 : Path [~12,0]
v26661 : Path [~11,0]
v26953 : Path [~3,0]
v26954 : Path [~4,0]
v26964 : Path [~5,0]
v26965 : Path [0,0]

Closure: v27077
v3325 : Path [0,0]

Closure: v27078
link to closure of v27077 : Path [0,0]

Closure: v27191
v27195 : Path [~3,0]
link to closure of v27088 : Path [0,~7]

Closure: v26721
v3325 : Path [0,~5]

Closure: v26737
v26736 : Path [~1,0]
link to closure of v27088 : Path [0,~4]

Closure: v26728
v3325 : Path [~1,0]
v26736 : Path [0,0]

Closure: v26733
v3325 : Path [~5,0]
v26736 : Path [0,0]

Closure: v27168
link to closure of v26728 : Path [0,0]

Closure: v26744
v3325 : Path [~1,0]
v26738 : Path [~4,0]
v27147 : Path [0,~3]

Closure: v26754
v3325 : Path [~1,0]
v26749 : Path [0,~2]

Closure: v26769
v26661 : Path [0,0]
[closing bignums/bigint.sml]
[Compiling bignums/realconst.sml]
signature PRIMREAL
signature REALCONST
functor RealConst
bignums/realconst.sml, line 229: Warning: match not exhaustive
        0 => ...
        1 => ...

Closure: v27656

Closure: v27213
v3325 : Path [~7,0]
v3577 : Path [~3,0]
v26661 : Path [~5,0]
v26896 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v27628
v3325 : Path [0,0]

Closure: v27614
v3325 : Path [~9,0]
v26896 : Path [~6,0]
v27627 : Path [~5,0]
v27647 : Path [0,0]

Closure: v27249
v3325 : Path [~13,0]
v27611 : Path [~12,0]
v27612 : Path [~11,0]
v27613 : Path [~7,0]
v27646 : Path [~5,0]
v27648 : Path [0,0]

Closure: v27578
v27614 : Path [~10,0]
v27646 : Path [~7,0]
v27650 : Path [~3,0]
link to closure of v3325 : Path [0,0]

Closure: v27570
link to closure of v3325 : Path [0,0]

Closure: v27566
v27268 : Path [~19,0]
link to closure of v3325 : Path [0,0]

Closure: v27563
v27268 : Path [~19,0]
link to closure of v3325 : Path [0,0]

Closure: v27523 v27546 v27279
v3325 : Path [~18,0]
v26661 : Path [~19,0]
v27267 : Path [~24,0]
v27268 : Path [~22,0]
v27562 : Path [~21,0]
v27565 : Path [~20,0]
v27567 : Path [~17,0]
v27570 : Path [0,0]

Closure: v27500
v3325 : Path [~28,0]
v27521 : Path [~27,0]
v27522 : Path [~7,0]
v27646 : Path [~5,0]
v27648 : Path [~4,0]
v27649 : Path [0,0]

Closure: v27372 v27377 v27396
v3325 : Path [~1,0]
v26896 : Path [~30,0]
v27213 : Path [~29,0]
v27317 : Path [~26,0]
v27500 : Path [~10,0]
v27523 : Path [~8,0]
v27614 : Path [~3,0]
v27628 : Path [0,0]

Closure: v27335
link to closure of v27372 : Path [0,~2]

Closure: v27412
v3325 : Path [0,~2]

Closure: v27345
link to closure of v27412 : Path [0,0]

Closure: v27413
link to closure of v27412 : Path [0,0]

Closure: v27304 v27310
v3325 : Path [0,0]

Closure: v27532 v27296
v26661 : Path [~5,0]
v27538 : Path [0,0]

Closure: v27571
v27269 : Path [~1,0]
link to closure of v27570 : Path [0,0]

Closure: v27261
v27260 : Path [~1,0]
link to closure of v27578 : Path [0,0]

Closure: v27245
v3325 : Path [0,0]

Closure: v27636 v27227
v3325 : Path [~6,0]
v26896 : Path [~5,0]
v27639 : Path [~3,0]
v27640 : Path [0,0]
[closing bignums/realconst.sml]
[Compiling build/invoke.sml]
signature CODES
signature INVOKE
functor Invoke
build/invoke.sml, line 536: Warning: binding not exhaustive
        pervStrs as STRvar {access=PATH <pat>,...} :: _ = ...
build/invoke.sml, line 536: Warning: match not exhaustive
        STRB {strvar=STRvar {access=LVAR <pat>,name=name,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        STRB {strvar=STRvar {access=LVAR <pat>,name=name,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        FCTB {fctvar=FCTvar {access=LVAR <pat>,name=name,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        STRvar {binding=STRstr {table=table,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        STRB {strvar=STRvar {access=LVAR <pat>,name=name,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        STRB {strvar=STRvar {access=LVAR <pat>,name=name,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        FCTB {fctvar=FCTvar {access=LVAR <pat>,name=name,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        SIGdec _ => ...
        STRdec sbs => ...
        ABSdec sbs => ...
        FCTdec fbs => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        sb as STRB {strvar=STRvar {access=<pat>,name=<pat>,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        sb as STRB {strvar=STRvar {access=<pat>,name=<pat>,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        fb as FCTB {fctvar=FCTvar {access=<pat>,name=<pat>,...},...} => ...
build/invoke.sml, line 536: Warning: match not exhaustive
        SIGdec _ => ...
        STRdec sbs => ...
        ABSdec sbs => ...
        FCTdec fbs => ...

Closure: v28796

Closure: v27674
v3325 : Path [~47,0]
v3487 : Path [~41,0]
v3835 : Path [~23,0]
v4005 : Path [~25,0]
v4475 : Path [~29,0]
v4753 : Path [~19,0]
v5192 : Path [~45,0]
v5723 : Path [~9,0]
v5833 : Path [~13,0]
v8143 : Path [~3,0]
v8538 : Path [~15,0]
v9117 : Path [~39,0]
v9727 : Path [~21,0]
v11292 : Path [~27,0]
v12594 : Path [~17,0]
v15281 : Path [~37,0]
v16361 : Path [~43,0]
v18371 : Path [~5,0]
v18760 : Path [~35,0]
v19547 : Path [~11,0]
v23387 : Path [~31,0]
v23973 : Path [~33,0]
v25320 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v28745 v28760
v3325 : Path [~6,0]
v3487 : Path [~5,0]
v4005 : Path [0,0]

Closure: v28740
v28742 : Path [~12,0]
link to closure of v3325 : Path [0,0]

Closure: v28733
v3325 : Path [~13,0]
v28741 : Path [~12,0]
v28742 : Path [~11,0]
v28743 : Path [0,0]

Closure: v28708 v28715 v28723 v28727
v3325 : Path [~16,0]
v4475 : Path [0,0]

Closure: v28406 v28429 v28438 v28457 v28538 v28636 v28647 v28658 v28677 v28691 v27834
v3325 : Path [~1,0]
v3487 : Path [~3,0]
v4475 : Path [~4,0]
v5192 : Path [~9,0]
v9117 : Path [~19,0]
v11292 : Path [~18,0]
v16361 : Path [~18,1]
v18760 : Path [~16,0]
v19547 : Path [~11,0]
v23387 : Path [~10,0]
v23973 : Path [~8,1]
v27674 : Path [~7,0]
v27677 : Path [0,0]

Closure: v27853 v27881
v3325 : Path [~20,10]
v3487 : Path [~23,0]
v5833 : Path [~22,0]
v27834 : Path [~21,0]
v28385 : Path [0,0]

Closure: v28198
v9117 : Path [0,0]

Closure: v28157
v3325 : Path [~32,0]
v3835 : Path [~31,0]
v9117 : Path [~30,0]
v9727 : Path [~29,0]
v28196 : Path [~28,0]
v28197 : Path [~27,0]
v28198 : Path [~26,0]
v28204 : Path [~25,0]
v28208 : Path [~20,0]
v28209 : Path [~20,3]
v28213 : Path [0,0]

Closure: v27982 v28065 v28074 v28083 v28097 v28114 v28134
v3325 : Path [~1,0]
v3487 : Path [~3,0]
v4475 : Path [~9,0]
v5192 : Path [~24,1]
v9117 : Path [~38,0]
v11292 : Path [~37,0]
v15281 : Path [~36,0]
v16361 : Path [~34,0]
v18760 : Path [~33,0]
v23387 : Path [~18,1]
v23973 : Path [~15,0]
v27674 : Path [~10,0]
v27677 : Path [0,0]

Closure: v28137
v3325 : Path [~8,0]
v28141 : Path [~7,0]
v28142 : Path [0,~6]

Closure: v28105
link to closure of v27982 : Path [0,~4]

Closure: v27995 v28007 v28019 v27961 v27977
v3325 : Path [0,0]

Closure: v27959
v3325 : Path [~11,0]
v28048 : Path [0,~3]

Closure: v27972
v3325 : Path [0,0]

Closure: v28225
link to closure of v27853 : Path [0,~1]

Closure: v28239
link to closure of v27853 : Path [0,~1]

Closure: v28261
link to closure of v27853 : Path [0,~1]

Closure: v28274
link to closure of v27853 : Path [0,~1]

Closure: v28287
link to closure of v27853 : Path [0,~1]

Closure: v28309
link to closure of v27853 : Path [0,~1]

Closure: v28219
link to closure of v27853 : Path [0,~1]

Closure: v28300
link to link to closure of v27853 : Path [0,0]

Closure: v28343
link to closure of v27853 : Path [0,0]

Closure: v27836
v28405 : Path [~1,0]
link to closure of v28406 : Path [0,~10]

Closure: v28611 v28624 v27778
v3325 : Path [~5,0]
v3487 : Path [~3,0]
v4475 : Path [~4,0]
v5192 : Path [0,~4]

Closure: v28552
link to closure of v28611 : Path [0,~2]

Closure: v28570
link to closure of v28611 : Path [0,~2]

Closure: v28588
link to closure of v28611 : Path [0,~2]

Closure: v28527 v27797
v3325 : Path [~1,0]
v4475 : Path [~4,0]
v5192 : Path [0,~3]

Closure: v28472
link to closure of v28527 : Path [0,~1]

Closure: v28489
link to closure of v28527 : Path [0,~1]

Closure: v28506
link to closure of v28527 : Path [0,~1]

Closure: v28450
link to closure of v28406 : Path [0,~2]

Closure: v28431
link to closure of v28406 : Path [0,~1]

Closure: v28422
link to closure of v28406 : Path [0,0]

Closure: v28410
v3325 : Path [~10,0]
v28413 : Path [0,0]

Closure: v27715
v27714 : Path [~1,0]
link to closure of v28708 : Path [0,0]

Closure: v28747
v3325 : Path [0,0]
[closing build/invoke.sml]
[Compiling vax/vaxcoder.sig]
signature VAXCODER
[closing vax/vaxcoder.sig]
[Compiling vax/vaxpeep.sml]
functor VaxPeephole

Closure: v29233

Closure: v28867
v3325 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v29202
v28867 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v28986 v28989 v28992 v28995 v28998 v29001 v29004 v29007 v29010 v29013 v29016 v29019 v29022 v29025 v29028 v29031 v29034 v29037 v29040 v29043 v29046 v29049 v29052 v29055 v29058 v29061 v29064 v29067 v29070 v29073 v29076 v29079 v29082 v29085 v29088 v29091 v29094 v29097 v29100 v29103 v29132 v29145 v29158 v29168 v28880 v28902
v3325 : Path [~1,0]
v28867 : Path [~5,0]
v29199 : Path [~4,0]
v29201 : Path [~3,0]
v29202 : Path [0,0]

Closure: v29213
link to closure of v29202 : Path [0,0]

Closure: v29208
link to closure of v29202 : Path [0,0]
[closing vax/vaxpeep.sml]
[Compiling vax/vaxmcode.sml]
signature BASICVAX
structure BasicVax
vax/vaxmcode.sml, line 105: Warning: match not exhaustive
        (MODE,2,s,d) => ...
        (MODE,3,s,d) => ...
        (MODE,5,s,d) => ...
        (WHICH (ref i,_,_),_,_,_) => ...
        (COND _,1,s,d) => ...
        (COND _,4,s,d) => ...
        (COND _,7,s,d) => ...
        (JBR,2,s,d) => ...
        (JBR,3,s,d) => ...
        (JBR,6,s,d) => ...

Closure: v29398

Closure: v29302 v29340 v29370 v29377 v29391 v29254
v3325 : Path [~5,0]
v29249 : Path [~6,0]
BOGUS : Path [0,0]

Closure: v29355
v3325 : Path [~4,0]
v29365 : Path [0,~1]
structure VaxMCode
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        address lab => ...
        displace (k,reg 15) => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        displace (i,reg 15) => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        displace (i,reg 15) => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        (immed i,arg2,arg3) => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        (immed 0,arg,address lab) => ...
        (arg1,arg2,address lab) => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        (immed 0,arg,address lab) => ...
        (arg1,arg2,address lab) => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        address lab => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        1 => ...
        2 => ...
        4 => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        1 => ...
        2 => ...
        4 => ...
vax/vaxmcode.sml, line 306: Warning: match not exhaustive
        direct (reg r) => ...
        autoinc (reg r) => ...
        autodec (reg r) => ...
        immed i => ...
        displace (i,reg r) => ...
        deferred (i,reg r) => ...
        index (ea,reg r) => ...

Closure: v30011

Closure: v29980
v3325 : Path [~11,0]
v29301 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v29976
v3487 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v29940 v29961
v3325 : Path [~11,0]
v26661 : Path [~7,0]
v29301 : Path [~3,0]
v29427 : Path [~15,0]
v29976 : Path [~14,0]
BOGUS : Path [0,0]

Closure: v29658 v29675 v29685 v29695 v29699 v29703 v29707 v29711 v29723 v29727 v29731 v29735 v29748 v29752 v29755 v29767 v29773 v29796 v29800 v29811 v29838 v29865 v29869 v29875 v29881 v29890 v29934 v29466
v3325 : Path [~11,0]
v29301 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v29614 v29620 v29623 v29627 v29631 v29635 v29639 v29643 v29647
v29301 : Path [~3,0]
v29773 : Path [~16,16]
v29881 : Path [~16,24]
v29890 : Path [~16,25]
BOGUS : Path [0,0]

Closure: v29662
v29671 : Path [~3,0]
v29672 : Path [~4,0]
link to closure of v29658 : Path [0,0]

Closure: v29967 v29434
v3325 : Path [~3,0]
v29971 : Path [~4,0]
v29972 : Path [0,~1]

Closure: v29943
v3325 : Path [~6,0]
v26661 : Path [~3,0]
v29301 : Path [~4,0]
v29954 : Path [0,0]

Closure: v29420
v3325 : Path [~1,0]
v29301 : Path [~3,0]
v29417 : Path [0,0]
[closing vax/vaxmcode.sml]
[Compiling vax/vaxascode.sml]
structure VaxAssem

Closure: v30017
structure VaxAsCode
vax/vaxascode.sml, line 154: Warning: match not exhaustive
        (immed i,arg2,arg3) => ...

Closure: v30581

Closure: v30466 v30469 v30481 v30493 v30502 v30541 v30545 v30548 v30567 v30572 v30061
v3325 : Path [~5,0]
v30013 : Path [~3,0]
v30576 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v30233 v30236 v30239 v30242 v30246 v30250 v30254 v30258 v30262 v30266 v30270 v30274 v30278 v30282 v30286 v30290 v30294 v30298 v30302 v30306 v30310 v30314 v30318 v30328 v30332 v30336 v30340 v30344 v30348 v30351 v30360 v30364 v30378 v30382 v30386 v30400 v30414 v30418 v30422 v30428 v30433 v30438 v30441 v30445 v30449 v30453
v3325 : Path [~5,0]
v30464 : Path [~10,0]
v30465 : Path [~9,0]
v30469 : Path [~8,1]
v30481 : Path [~8,2]
v30493 : Path [~8,3]
v30502 : Path [~8,4]
v30548 : Path [~8,7]
v30572 : Path [~8,9]
BOGUS : Path [0,0]
[closing vax/vaxascode.sml]
[Compiling vax/vaxprim.sml]
signature MACHINEPRIM
functor VaxPrim
vax/vaxprim.sml, line 274: Warning: binding contains no variables
        () = ...
vax/vaxprim.sml, line 274: Warning: binding not exhaustive
        VARbind (VALvar {access=INLINE i,...}) = ...
vax/vaxprim.sml, line 274: Warning: match not exhaustive
        ((s,2),f) => ...
vax/vaxprim.sml, line 274: Warning: binding not exhaustive
        VARbind (VALvar {access=INLINE i,...}) = ...

Closure: v30898

Closure: v30585
v3325 : Path [~11,0]
v4753 : Path [~3,0]
v8538 : Path [~5,0]
v9727 : Path [~7,0]
v23973 : Path [~9,0]
BOGUS : Path [0,0]

Closure: v30888
v30589 : Path [~3,0]
link to closure of v3325 : Path [0,0]

Closure: v30817 v30825 v30845 v30865 v30871 v30877
v3325 : Path [~1,0]
v4753 : Path [~3,0]
v8538 : Path [~6,0]
v9727 : Path [~5,0]
v23973 : Path [~4,0]
v30585 : Path [0,0]

Closure: v30815
link to closure of v3325 : Path [0,0]

Closure: v30814
link to closure of v3325 : Path [0,0]

Closure: v30813
v30585 : Path [~1,0]
v30817 : Path [~7,0]
link to closure of v3325 : Path [0,0]

Closure: v30808
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30804
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30801
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30793
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30791
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30785
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30778
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30774
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30757
v30585 : Path [~1,0]
v30825 : Path [~7,1]
v30845 : Path [~7,2]
link to closure of v3325 : Path [0,0]

Closure: v30751
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30747
v30585 : Path [~1,0]
v30817 : Path [~7,0]
link to closure of v3325 : Path [0,0]

Closure: v30738
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30731
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30726
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30717
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30710
v30585 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v30703
link to closure of v3325 : Path [0,0]

Closure: v30702
v30585 : Path [~1,0]
v30816 : Path [~8,0]
link to closure of v3325 : Path [0,0]

Closure: v30684
v30585 : Path [~1,0]
v30816 : Path [~8,0]
v30845 : Path [~7,2]
link to closure of v3325 : Path [0,0]

Closure: v30663
v30585 : Path [~1,0]
v30825 : Path [~7,1]
v30845 : Path [~7,2]
link to closure of v3325 : Path [0,0]

Closure: v30675
v30678 : Path [~4,0]
link to closure of v30663 : Path [0,0]

Closure: v30630
v30678 : Path [~4,0]
link to closure of v30663 : Path [0,0]

Closure: v30691
v30694 : Path [~4,0]
link to closure of v30684 : Path [0,0]

Closure: v30765
v30768 : Path [~4,0]
link to closure of v30757 : Path [0,0]

Closure: v30620
v30768 : Path [~4,0]
link to closure of v30757 : Path [0,0]

Closure: v30848
v30860 : Path [~4,0]
v30862 : Path [~6,0]
link to closure of v30817 : Path [0,~2]

Closure: v30612
v30839 : Path [~4,0]
link to closure of v30817 : Path [0,~1]
[closing vax/vaxprim.sml]
[Compiling vax/vaxgen.sml]
functor VaxGen
vax/vaxgen.sml, line 180: Warning: match not exhaustive
        i :: nil => ...
        i :: 0 :: (more as _ :: _) => ...
        i :: (more as _ :: _) => ...
vax/vaxgen.sml, line 180: Warning: match not exhaustive
        0 :: nil => ...
        j :: nil => ...
        j :: 0 :: (more as _ :: _) => ...
        j :: (more as _ :: _) => ...

Closure: v31336

Closure: v30902
v3325 : Path [~5,0]
v30633 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v31185 v31188 v31195 v31199 v31214 v31224 v31239 v31245 v31256 v31329 v30912
v3325 : Path [~1,0]
v30902 : Path [0,0]

Closure: v31123 v31128 v31137 v31154 v31162 v31173 v31179
v3325 : Path [~1,0]
v30902 : Path [~4,7]
v31245 : Path [0,0]

Closure: v31020 v31026 v31035 v31046 v31050 v31059 v31065 v31071 v31086 v31096 v31100 v31106 v31112 v31119
v3325 : Path [~1,0]
v30902 : Path [~7,0]
v31122 : Path [0,0]

Closure: v30963
v30902 : Path [~4,0]
v31150 : Path [~5,0]
v31151 : Path [0,~2]
[closing vax/vaxgen.sml]
[Compiling vax/vaxglue.sml]
structure VaxCodes

Closure: v31359

Closure: v31349
v29301 : Path [~5,0]
BOGUS : Path [0,0]
structure VaxGlue

Closure: v31365
[closing vax/vaxglue.sml]
[Compiling m68/m68coder.sig]
signature M68CODER
[closing m68/m68coder.sig]
[Compiling m68/m68peep.sml]
functor M68Peephole

Closure: v31812

Closure: v31437
v3325 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v31551 v31554 v31557 v31560 v31563 v31566 v31569 v31572 v31575 v31578 v31581 v31584 v31587 v31590 v31593 v31596 v31599 v31602 v31605 v31608 v31611 v31614 v31617 v31620 v31623 v31626 v31629 v31632 v31635 v31638 v31641 v31644 v31647 v31650 v31653 v31656 v31659 v31662 v31665 v31668 v31671 v31690 v31749 v31762 v31772 v31777 v31460
v3325 : Path [~1,0]
v31437 : Path [~4,0]
v31807 : Path [~3,0]
v31809 : Path [0,0]

Closure: v31710
link to closure of v31551 : Path [0,~46]
[closing m68/m68peep.sml]
[Compiling m68/m68mcode.sml]
signature BASICM68
structure BasicM68
m68/m68mcode.sml, line 102: Warning: match not exhaustive
        (Jcc opcode,2,s,d) => ...
        (Jcc opcode,4,s,d) => ...
        (Jcc opcode,6,s,d) => ...
        (LEA opcode,4,s,d) => ...
        (LEA opcode,8,s,d) => ...
        (FJcc cond,4,s,d) => ...
        (FJcc cond,6,s,d) => ...

Closure: v31948

Closure: v31877 v31908 v31922 v31938 v31842 v31851
v3325 : Path [~5,0]
v31828 : Path [~6,0]
BOGUS : Path [0,0]
structure M68MCode
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (src,dest as Direct (FloatReg f)) => ...
        (src as Direct (FloatReg f),dest) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
        dest as Displace (AddrReg _,_) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
        arg as Displace (AddrReg _,_) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Address lab => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (Direct _,_) => ...
        (PreDec _,_) => ...
        (PostInc _,_) => ...
        (Immed _,_) => ...
        (Address lab,Direct (AddrReg a)) => ...
        (src,Direct (AddrReg a)) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (_,Direct (AddrReg _)) => ...
        (_,Immed _) => ...
        (Direct (DataReg d),dest) => ...
        (Immed i,dest) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (_,Immed _) => ...
        (src,Direct (DataReg d)) => ...
        (src,Direct (AddrReg a)) => ...
        (Immed i,dest) => ...
        (PostInc (AddrReg y),PostInc (AddrReg x)) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (src,Direct (DataReg d)) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (src,Direct (DataReg d)) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (_,Immed _) => ...
        (src as Immed i,dest as Direct (AddrReg a)) => ...
        (src,Direct (AddrReg a)) => ...
        (src as Immed i,dest) => ...
        (src,Direct (DataReg d)) => ...
        (Direct (DataReg d),dest) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (_,Immed _) => ...
        (src as Immed i,dest as Direct (AddrReg a)) => ...
        (src,Direct (AddrReg a)) => ...
        (src as Immed i,dest) => ...
        (src,Direct (DataReg d)) => ...
        (Direct (DataReg d),dest) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (Direct (AddrReg a),Direct (AddrReg b)) => ...
        (Direct (DataReg a),Direct (DataReg b)) => ...
        (Direct (AddrReg b),Direct (DataReg a)) => ...
        (Direct (DataReg a),Direct (AddrReg b)) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        (opcode,Direct (FloatReg a),Direct (FloatReg b)) => ...
        (opcode,src,Direct (FloatReg f)) => ...
        (opcode,Direct (FloatReg f),dest) => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Immed i => ...
        Abs i => ...
        Direct _ => ...
        Displace (_,0) => ...
        PostInc _ => ...
        PreDec _ => ...
        Displace (_,i) => ...
        Index (_,disp,DataReg d,Word) => ...
        Index (_,disp,DataReg d,Long) => ...
        Index (_,disp,AddrReg d,Word) => ...
        Index (_,disp,AddrReg d,Long) => ...
        Address _ => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Direct (DataReg _) => ...
        Direct (AddrReg _) => ...
        Displace (AddrReg _,0) => ...
        PostInc (AddrReg _) => ...
        PreDec (AddrReg _) => ...
        Displace (AddrReg _,_) => ...
        Index (AddrReg _,_,_,_) => ...
        Abs _ => ...
        Immed _ => ...
        Address _ => ...
m68/m68mcode.sml, line 488: Warning: match not exhaustive
        Direct (DataReg d) => ...
        Direct (AddrReg a) => ...
        PostInc (AddrReg a) => ...
        PreDec (AddrReg a) => ...
        Displace (AddrReg a,_) => ...
        Index (AddrReg a,_,_,_) => ...
        Abs i => ...
        Immed _ => ...
        Address _ => ...

Closure: v32965

Closure: v32869 v32878 v32906
v3325 : Path [~11,0]
v31876 : Path [~3,0]
v31975 : Path [~37,0]
BOGUS : Path [0,0]

Closure: v32865
v3487 : Path [~5,0]
BOGUS : Path [0,0]

Closure: v32829 v32850
v3325 : Path [~11,0]
v26661 : Path [~7,0]
v31876 : Path [~3,0]
v31997 : Path [~40,0]
v32865 : Path [~39,0]
BOGUS : Path [0,0]

Closure: v32762 v32800
v3325 : Path [~11,0]
v31876 : Path [~3,0]
v31975 : Path [~37,0]
v32878 : Path [~38,1]
v32906 : Path [~38,2]
BOGUS : Path [0,0]

Closure: v32471 v32507 v32530 v32542 v32554 v32620 v32686 v32735 v32759
v3325 : Path [~11,0]
v31876 : Path [~3,0]
v32046 : Path [~42,0]
v32800 : Path [~41,1]
v32878 : Path [~38,1]
v32906 : Path [~38,2]
BOGUS : Path [0,0]

Closure: v32240 v32243 v32246 v32249 v32268 v32274 v32280 v32286 v32292 v32298 v32304 v32308 v32312 v32316 v32320 v32324 v32328 v32339 v32350 v32354 v32358 v32362 v32366 v32370 v32374 v32397 v32406 v32434
v3325 : Path [~11,0]
v31876 : Path [~3,0]
v32046 : Path [~42,0]
v32686 : Path [~43,6]
v32762 : Path [~41,0]
v32800 : Path [~41,1]
v32878 : Path [~38,1]
v32906 : Path [~38,2]
v32942 : Path [~28,0]
BOGUS : Path [0,0]

Closure: v32472
v31876 : Path [~3,0]
v32046 : Path [0,0]

Closure: v32856 v32004
v3325 : Path [~3,0]
v32860 : Path [~4,0]
v32861 : Path [0,~1]

Closure: v32832
v3325 : Path [~6,0]
v26661 : Path [~3,0]
v31876 : Path [~4,0]
v32843 : Path [0,0]

Closure: v31990
v3325 : Path [~1,0]
v31876 : Path [~3,0]
v31987 : Path [0,0]
[closing m68/m68mcode.sml]
[Compiling m68/m68ascode.sml]
structure M68Assem

Closure: v32971
structure M68AsCode
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as (src,dest as Direct (FloatReg <pat>)) => ...
        arg as (src as Direct (FloatReg <pat>),dest) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
        arg as Displace (AddrReg _,_) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
        arg as Displace (AddrReg a,i) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        (Direct _,_) => ...
        (PreDec _,_) => ...
        (PostInc _,_) => ...
        (Immed _,_) => ...
        (src as Address _,dest as Direct (AddrReg _)) => ...
        (src,dest as Direct (AddrReg a)) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        (_,Direct (AddrReg _)) => ...
        (_,Immed _) => ...
        (src as Direct (DataReg d),dest) => ...
        (src as Immed i,dest) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        (_,Immed _) => ...
        (src,dest as Direct (DataReg d)) => ...
        (src,dest as Direct (AddrReg a)) => ...
        (src as Immed i,dest) => ...
        (src as PostInc (AddrReg y),dest as PostInc (AddrReg x)) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        (_,Immed _) => ...
        (src as Immed i,dest as Direct (AddrReg a)) => ...
        (src,dest as Direct (AddrReg a)) => ...
        (src as Immed i,dest) => ...
        (src,dest as Direct (DataReg d)) => ...
        (src as Direct (DataReg d),dest) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        (_,Immed _) => ...
        (src as Immed i,dest as Direct (AddrReg a)) => ...
        (src,dest as Direct (AddrReg a)) => ...
        (src as Immed i,dest) => ...
        (src,dest as Direct (DataReg d)) => ...
        (src as Direct (DataReg d),dest) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        arg as (Direct (AddrReg a),Direct (AddrReg b)) => ...
        arg as (Direct (DataReg a),Direct (DataReg b)) => ...
        arg as (Direct (AddrReg b),Direct (DataReg a)) => ...
        arg as (Direct (DataReg a),Direct (AddrReg b)) => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        Immed i => ...
        Abs i => ...
        Direct r => ...
        Displace (ra,0) => ...
        PostInc ra => ...
        PreDec ra => ...
        Displace (r,i) => ...
        Index (ra,disp,r,Word) => ...
        Index (ra,disp,r,Long) => ...
        Address lab => ...
m68/m68ascode.sml, line 313: Warning: match not exhaustive
        DataReg 0 => ...
        DataReg 1 => ...
        DataReg 2 => ...
        DataReg 3 => ...
        DataReg 4 => ...
        DataReg 5 => ...
        DataReg 6 => ...
        DataReg 7 => ...
        AddrReg 0 => ...
        AddrReg 1 => ...
        AddrReg 2 => ...
        AddrReg 3 => ...
        AddrReg 4 => ...
        AddrReg 5 => ...
        AddrReg 6 => ...
        AddrReg 7 => ...
        FloatReg 0 => ...
        FloatReg 1 => ...
        FloatReg 2 => ...
        FloatReg 3 => ...
        FloatReg 4 => ...
        FloatReg 5 => ...
        FloatReg 6 => ...
        FloatReg 7 => ...

Closure: v33979

Closure: v33965 v33970
v3325 : Path [~5,0]
v33974 : Path [~7,0]
BOGUS : Path [0,0]

Closure: v33872 v33875 v33879 v33888 v33925 v33932 v33938
v3325 : Path [~5,0]
v32967 : Path [~3,0]
v33965 : Path [~8,0]
BOGUS : Path [0,0]

Closure: v33828 v33834 v33839 v33844 v33847 v33851 v33855 v33859
v3325 : Path [~5,0]
v33870 : Path [~35,0]
v33871 : Path [~34,0]
v33938 : Path [~33,6]
v33970 : Path [~8,1]
BOGUS : Path [0,0]

Closure: v33292 v33295 v33298 v33301 v33325 v33333 v33341 v33349 v33357 v33365 v33373 v33379 v33385 v33391 v33397 v33403 v33409 v33422 v33435 v33441 v33447 v33453 v33459 v33465 v33471 v33496 v33506 v33536 v33576 v33589 v33602 v33615 v33619 v33623 v33690 v33757 v33796 v33825
v3325 : Path [~5,0]
v33064 : Path [~37,0]
v33875 : Path [~33,1]
v33879 : Path [~33,2]
v33925 : Path [~33,4]
v33938 : Path [~33,6]
v33949 : Path [~24,0]
BOGUS : Path [0,0]
[closing m68/m68ascode.sml]
[Compiling m68/m68prim.sml]
signature MACHINEPRIM
structure M68options

Closure: v33987
functor M68prim
m68/m68prim.sml, line 301: Warning: binding contains no variables
        () = ...
m68/m68prim.sml, line 301: Warning: binding not exhaustive
        VARbind (VALvar {access=INLINE i,...}) = ...
m68/m68prim.sml, line 301: Warning: match not exhaustive
        ((s,2),f) => ...
m68/m68prim.sml, line 301: Warning: binding not exhaustive
        VARbind (VALvar {access=INLINE i,...}) = ...

Closure: v34327

Closure: v33988
v3325 : Path [~13,0]
v4753 : Path [~3,0]
v8538 : Path [~5,0]
v9727 : Path [~7,0]
v23973 : Path [~9,0]
v33984 : Path [~11,0]
BOGUS : Path [0,0]

Closure: v34316
v33992 : Path [~3,0]
link to closure of v3325 : Path [0,0]

Closure: v34245 v34253 v34273 v34293 v34299 v34305
v3325 : Path [~1,0]
v4753 : Path [~3,0]
v8538 : Path [~6,0]
v9727 : Path [~5,0]
v23973 : Path [~4,0]
v33988 : Path [0,0]

Closure: v34243
link to closure of v3325 : Path [0,0]

Closure: v34242
link to closure of v3325 : Path [0,0]

Closure: v34241
v33988 : Path [~1,0]
v34245 : Path [~7,0]
link to closure of v3325 : Path [0,0]

Closure: v34236
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34232
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34226
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34224
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34216
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34207
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34199
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34193
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34171
v33988 : Path [~1,0]
v34253 : Path [~7,1]
v34273 : Path [~7,2]
link to closure of v3325 : Path [0,0]

Closure: v34165
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34161
v33988 : Path [~1,0]
v34245 : Path [~7,0]
link to closure of v3325 : Path [0,0]

Closure: v34152
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34146
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34140
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34128
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34121
v33988 : Path [~1,0]
link to closure of v3325 : Path [0,0]

Closure: v34113
link to closure of v3325 : Path [0,0]

Closure: v34112
v33988 : Path [~1,0]
v34244 : Path [~8,0]
link to closure of v3325 : Path [0,0]

Closure: v34093
v33988 : Path [~1,0]
v34244 : Path [~8,0]
v34273 : Path [~7,2]
link to closure of v3325 : Path [0,0]

Closure: v34068
v33988 : Path [~1,0]
v34253 : Path [~7,1]
v34273 : Path [~7,2]
link to closure of v3325 : Path [0,0]

Closure: v34084
v34087 : Path [~4,0]
link to closure of v34068 : Path [0,0]

Closure: v34035
v34087 : Path [~4,0]
link to closure of v34068 : Path [0,0]

Closure: v34101
v34104 : Path [~4,0]
link to closure of v34093 : Path [0,0]

Closure: v34181
v34184 : Path [~4,0]
link to closure of v34171 : Path [0,0]

Closure: v34024
v34184 : Path [~4,0]
link to closure of v34171 : Path [0,0]

Closure: v34276
v34288 : Path [~4,0]
v34290 : Path [~6,0]
link to closure of v34245 : Path [0,~2]

Closure: v34015
v34267 : Path [~4,0]
link to closure of v34245 : Path [0,~1]
[closing m68/m68prim.sml]
[Compiling m68/m68gen.sml]
functor M68Gen
m68/m68gen.sml, line 182: Warning: match not exhaustive
        i :: nil => ...
        i :: more => ...
m68/m68gen.sml, line 182: Warning: match not exhaustive
        0 :: nil => ...
        j :: nil => ...
        j :: more => ...

Closure: v34713

Closure: v34331
v3325 : Path [~5,0]
v34038 : Path [~3,0]
BOGUS : Path [0,0]

Closure: v34612 v34616 v34623 v34627 v34639 v34649 v34664 v34670 v34681 v34706 v34339
v3325 : Path [~1,0]
v34331 : Path [0,0]

Closure: v34550 v34558 v34578 v34588 v34599 v34605
v3325 : Path [~1,0]
v34331 : Path [~4,7]
v34670 : Path [0,0]

Closure: v34445 v34451 v34460 v34470 v34474 v34483 v34489 v34495 v34510 v34520 v34524 v34530 v34536 v34543
v3325 : Path [~1,0]
v34331 : Path [~8,0]
v34546 : Path [0,0]

Closure: v34388
v34331 : Path [~4,0]
v34574 : Path [~5,0]
v34575 : Path [0,~1]
[closing m68/m68gen.sml]
[Compiling m68/m68glue.sml]
structure M68Codes

Closure: v34737

Closure: v34727
v31876 : Path [~5,0]
BOGUS : Path [0,0]
structure M68Glue

Closure: v34743
[closing m68/m68glue.sml]
[Compiling build/compile.sml]
functor Compile
build/compile.sml, line 278: Warning: match not exhaustive
        "0" => ...
        "1" => ...
        "2" => ...
        "3" => ...
        "4" => ...
        "5" => ...
        "6" => ...
        "7" => ...
        "8" => ...
        "9" => ...
build/compile.sml, line 278: Warning: binding not exhaustive
        STRvar {binding=STRstr {table=table,...},...} = ...

Closure: v35207

Closure: v34744
v3325 : Path [~21,0]
v3487 : Path [~3,0]
v3666 : Path [~11,0]
v4475 : Path [~19,0]
v4753 : Path [~5,0]
v5723 : Path [~15,0]
v5833 : Path [~9,0]
v9727 : Path [~7,0]
v23973 : Path [~17,0]
v33984 : Path [~13,0]
BOGUS : Path [0,0]

Closure: v35178 v34755 v34759
v3325 : Path [0,0]

Closure: v35145
v3325 : Path [0,0]

Closure: v35043 v35068 v35108
v3325 : Path [~3,1]
v3487 : Path [~3,2]
v3666 : Path [~7,0]
v4753 : Path [~6,0]
v5833 : Path [0,0]

Closure: v35028 v35032 v35036
v3325 : Path [~1,0]
v34744 : Path [~9,0]
v35042 : Path [0,0]

Closure: v35021
v3325 : Path [~13,0]
v35027 : Path [0,0]

Closure: v34965 v34980 v34984 v34990 v35008
v3325 : Path [~1,0]
v34744 : Path [~3,1]
v34755 : Path [~3,2]
v34759 : Path [~15,0]
v34818 : Path [~16,0]
v35020 : Path [0,0]

Closure: v34886 v34914 v34928 v34932 v34937 v34952
v3325 : Path [~1,0]
v4475 : Path [~15,0]
v34744 : Path [~18,0]
v34818 : Path [~17,2]
v34964 : Path [~14,0]
v34984 : Path [~13,0]
v35021 : Path [~12,0]
v35027 : Path [~12,1]
v35028 : Path [~12,2]
v35032 : Path [~11,0]
v35036 : Path [~10,0]
v35040 : Path [~9,0]
v35041 : Path [0,0]

Closure: v34857
v3325 : Path [~1,0]
v34818 : Path [0,~5]

Closure: v34863
v3325 : Path [0,~4]

Closure: v34824
v3325 : Path [~1,0]
v34818 : Path [0,~4]

Closure: v34831
v3325 : Path [0,~3]

Closure: v34967 v34974
v3325 : Path [0,0]

Closure: v34968
link to closure of v34967 : Path [0,0]

Closure: v34762
v3325 : Path [~1,0]
v34755 : Path [0,0]
[closing build/compile.sml]
[Compiling build/glue.sml]
functor Interact

Closure: v35218

Closure: v35213
BOGUS : Path [0,0]
structure CompVax

Closure: v35224
structure CompM68

Closure: v35230
structure IntVax

Closure: v35236
structure IntM68

Closure: v35242
[closing build/glue.sml]
[globalhandle := true]
[dumpCore := false]
[Exporting to upto.all]
hello there
[summary()]
16296 lines
parse, 209.283328s
translate, 12.083334s
codeopt, 11.666664s
codegen, 131.650004s
execution, 0.0s
total 364.683330s
Garbage collection information:
130 minor collections, 5 major collections
27350056 collected from 466712180 possible (5.9%)
Total process time was 413.450000
Total garbage collection time was 41.200000 (10.0%)
