= The `ControlRegistry` structure
:Author: John Reppy
:Date: {release-date}
:stem: latexmath
:source-highlighter:  CONTROL_REGISTRY
:VERSION: {smlnj-version}

The `ControlRegistry` structure ...

== Synopsis

[source,sml]
------------
signature CONTROL_REGISTRY
structure ControlRegistry : CONTROL_REGISTRY
------------

== Interface

[source,sml]
------------
    type registry

    type control_info = { envName : string option }

    val new : {
	    help : string	(* registry's description *)
	  } -> registry

  (* register a control *)
    val register : registry -> {
	    ctl : string Controls.control,
	    envName : string option
	  } -> unit

  (* register a set of controls *)
    val registerSet : registry -> {
	    ctls : (string, 'a) ControlSet.control_set,
	    mkEnvName : string -> string option
	  } -> unit

  (* nest a registry inside another registry *)
    val nest : registry -> {
	    prefix : string option,
	    pri : Controls.priority,	(* registry's priority *)
            obscurity : int,		(* registry's detail level; higher means *)
					(* more obscure *)
	    reg : registry
	  } -> unit

  (* find a control *)
    val control : registry -> string list -> string Controls.control option

  (* initialize the controls in the registry from the environment *)
    val init : registry -> unit

    datatype registry_tree = RTree of {
	path : string list,
	help : string,
	ctls : { ctl : string Controls.control, info : control_info } list,
	subregs : registry_tree list
      }

  (* get the registry-tree representation of a registry; an optional obscurity
   * argument may be supplied to filter out obscure options.
   *)
    val controls : (registry * int option) -> registry_tree
------------

== Description

    type registry

    type control_info = { envName : string option }

    val new : {
	    help : string	(* registry's description *)
	  } \-> registry

  (* register a control *)
    val register : registry \-> {
	    ctl : string Controls.control,
	    envName : string option
	  } \-> unit

  (* register a set of controls *)
    val registerSet : registry \-> {
	    ctls : (string, 'a) ControlSet.control_set,
	    mkEnvName : string \-> string option
	  } \-> unit

  (* nest a registry inside another registry *)
    val nest : registry \-> {
	    prefix : string option,
	    pri : Controls.priority,	(* registry's priority *)
            obscurity : int,		(* registry's detail level; higher means *)
					(* more obscure *)
	    reg : registry
	  } \-> unit

  (* find a control *)
    val control : registry \-> string list \-> string Controls.control option

  (* initialize the controls in the registry from the environment *)
    val init : registry \-> unit

    datatype registry_tree = RTree of {
	path : string list,
	help : string,
	ctls : { ctl : string Controls.control, info : control_info } list,
	subregs : registry_tree list
      }

  (* get the registry-tree representation of a registry; an optional obscurity
   * argument may be supplied to filter out obscure options.
   *)
    val controls : (registry * int option) \-> registry_tree

== See Also

link:controls-lib.html[__The Controls Library__]
